"""Strict R-parity test for: llh_in_cluster

Added: 2026-03-11
Status: PASSING

R function: llh_in_cluster (log-likelihood calculation in r_code/functions.R)
Python equivalent: weatherisk.estimation.llh_in_cluster

Acceptance standard (docs/python_r_parity_migration_plan.md):
    max |Python - R| < 1e-14

Observed max abs diff: 5.33e-15 (within acceptance).

Note: This test uses the LEC cluster assignments from R, the raw simulation
data, and the per-cluster estimate parameters from R. The log-likelihood is
computed with average=True and max_dist set to 4 * grid spacing (matching R).
Simulation data is in R's column-major ordering and must be re-mapped.

Fixtures:
    tests/reference_data/llh_in_clusters_lec.csv — per-cluster llh values
    tests/reference_data/clusters_lec.csv — cluster assignments (R order)
    tests/reference_data/simulation_nonstat_seed42.csv — simulation data
    Generated by: tests/generate_r_reference.R
"""

import numpy as np
import pandas as pd
from tests.parity.conftest import REF, STRICT_ATOL, skip_if_no_ref


class TestParityLlhInCluster:

    def setup_method(self):
        skip_if_no_ref()
        from weatherisk.grid import Grid

        self.grid = Grid(resolution=10)

    def test_llh_in_cluster_strict(self):
        """llh_in_cluster matches R to < 1e-14 for each LEC cluster."""
        from weatherisk.estimation import llh_in_cluster

        ref_llh = pd.read_csv(REF / "llh_in_clusters_lec.csv")
        ref_clusters = pd.read_csv(REF / "clusters_lec.csv")

        # Load simulation data in R column-major order
        sim_ref = pd.read_csv(REF / "simulation_nonstat_seed42.csv")
        sim_cols = [c for c in sim_ref.columns if c.startswith("sim")]
        n_sim = len(sim_cols)
        n = self.grid.n_grid

        sim_data = np.zeros((n, n_sim))
        for k, col in enumerate(sim_cols):
            sim_data[:, k] = sim_ref[col].values

        # Reshape to 3D in R's row/col layout
        sim_3d = np.zeros((self.grid.nrow, self.grid.ncol, n_sim))
        for r_idx in range(n):
            r_i = r_idx % self.grid.nrow
            r_j = r_idx // self.grid.nrow
            sim_3d[r_i, r_j, :] = sim_data[r_idx, :]

        r_clusters = ref_clusters["cluster"].values
        resolution = self.grid.resolution
        max_dist = 4 * (
            (self.grid.x_ax[-1] - self.grid.x_ax[0]) / (resolution - 1)
        )

        max_diff = 0.0
        for _, row in ref_llh.iterrows():
            cl = int(row["cluster"])
            locest = np.array([row["a"], row["b"], row["g"]])

            # R indices for this cluster (0-based in the column-major flat array)
            which_cl_r = np.where(r_clusters == cl)[0]

            # Coordinates in R's column-major layout
            X_cl = self.grid.X.flatten("F")[which_cl_r]
            Y_cl = self.grid.Y.flatten("F")[which_cl_r]

            # Build z matrix: (n_points_in_cluster, n_sim)
            z_cl = np.zeros((len(which_cl_r), n_sim))
            for k, r_idx in enumerate(which_cl_r):
                r_i = r_idx % self.grid.nrow
                r_j = r_idx // self.grid.nrow
                z_cl[k, :] = sim_3d[r_i, r_j, :]

            py_llh = llh_in_cluster(
                z_cl,
                df=5.0,
                alpha=1.0,
                X=X_cl,
                Y=Y_cl,
                locest=locest,
                max_dist=max_dist,
                average=True,
            )

            diff = abs(py_llh - row["llh"])
            max_diff = max(max_diff, diff)
            assert diff < STRICT_ATOL, (
                f"llh_in_cluster(cluster={cl}): "
                f"Python={py_llh}, R={row['llh']}, diff={diff}"
            )

        print(f"\nllh_in_cluster max abs diff: {max_diff:.2e}")
