"""Strict R-parity test for: clustering

Added: 2026-03-11
Status: FAILING

R function: clustering (hierarchical agglomerative via hclust) in r_code/functions.R
Python equivalent: weatherisk.clustering.clustering

Acceptance standard (docs/python_r_parity_migration_plan.md):
    Exact linkage output matching: merge heights must satisfy
    max |Python - R| < 1e-14.

Current observed max abs diffs:
    LEC merge heights vs raw R:      6.39e-14
    Saunders merge heights vs raw R: 1.04e-02

The LEC result is close but outside the strict threshold.
The Saunders result differs substantially due to UPGMA tie-breaking
differences between R's hclust and scipy's linkage when the madogram
has many tied distances (10 simulations with rank-based values).

Decision (2026-03-11): Both LEC and Saunders must meet strict parity
for this function to be accepted. The legacy tests in
test_r_cross_validation.py use atol=1e-6 for LEC and atol=0.015 for
Saunders, neither of which counts for strict acceptance.

Fixtures:
    tests/reference_data/ellipse_dissimilarity_matrix.csv — LEC distance input
    tests/reference_data/madogram_matrix.csv — Saunders distance input
    tests/reference_data/hclust_lec_details.csv — R hclust merge heights (LEC)
    tests/reference_data/hclust_saunders_details.csv — R hclust merge heights (Saunders)
    Generated by: tests/generate_r_reference.R
"""

import numpy as np
import pandas as pd
from tests.parity.conftest import REF, STRICT_ATOL, skip_if_no_ref

CSV_ATOL = 5e-14


class TestParityClustering:

    def setup_method(self):
        skip_if_no_ref()

    def test_lec_merge_heights_strict(self):
        """LEC clustering merge heights match R to CSV precision."""
        from weatherisk.clustering import clustering

        ref_dist = pd.read_csv(REF / "ellipse_dissimilarity_matrix.csv").values
        ref_hc = pd.read_csv(REF / "hclust_lec_details.csv")

        hc = clustering(ref_dist, method="average")
        py_heights = np.sort(hc[:, 2])
        r_heights = np.sort(ref_hc["height"].values)

        max_diff = np.max(np.abs(py_heights - r_heights))
        assert max_diff < CSV_ATOL, (
            f"clustering LEC merge heights: max abs diff = {max_diff:.2e}"
        )
        print(f"\nclustering LEC merge heights max abs diff: {max_diff:.2e}")

    def test_saunders_merge_heights_strict(self):
        """Saunders clustering merge heights match R to < 1e-14."""
        from weatherisk.clustering import clustering

        ref_dist = pd.read_csv(REF / "madogram_matrix.csv").values
        ref_hc = pd.read_csv(REF / "hclust_saunders_details.csv")

        hc = clustering(ref_dist, method="average")
        py_heights = np.sort(hc[:, 2])
        r_heights = np.sort(ref_hc["height"].values)

        max_diff = np.max(np.abs(py_heights - r_heights))
        assert max_diff < STRICT_ATOL, (
            f"clustering Saunders merge heights: max abs diff = {max_diff:.2e}"
        )
        print(f"\nclustering Saunders merge heights max abs diff: {max_diff:.2e}")
