"""Strict R-parity test for: pairwise_density_summand

Added: 2026-03-11
Status: PASSING

R function: pairwise_density_summand(z1, z2, x, y, df, alpha, a, b, g)
            in r_code/functions.R
Python equivalent: weatherisk.density.pairwise_density_summand

Acceptance standard (docs/python_r_parity_migration_plan.md):
    max |Python - R| < 1e-14

Observed max abs diff: 5.33e-15 (within acceptance).

Note: The legacy test in test_r_cross_validation.py uses atol=1e-8.
This strict test uses atol < 1e-14 as required by the migration plan.

Fixture: tests/reference_data/pairwise_density_test_cases.csv
    Generated by: tests/generate_r_reference.R
    Columns: z1, z2, x, y, df, alpha, a, b, g, density_value
"""

import pandas as pd
from tests.parity.conftest import REF, STRICT_ATOL, skip_if_no_ref


class TestParityPairwiseDensitySummand:

    def setup_method(self):
        skip_if_no_ref()

    def test_pairwise_density_summand_strict(self):
        """pairwise_density_summand matches R to < 1e-14 on all cases."""
        from weatherisk.density import pairwise_density_summand

        ref = pd.read_csv(REF / "pairwise_density_test_cases.csv")
        max_diff = 0.0
        for _, row in ref.iterrows():
            py_val = pairwise_density_summand(
                row["z1"], row["z2"], row["x"], row["y"],
                row["df"], row["alpha"], row["a"], row["b"], row["g"],
            )
            diff = abs(py_val - row["density_value"])
            max_diff = max(max_diff, diff)
            assert diff < STRICT_ATOL, (
                f"pairwise_density_summand(z1={row['z1']}, z2={row['z2']}, "
                f"x={row['x']}, y={row['y']}, a={row['a']}, b={row['b']}, "
                f"g={row['g']}): Python={py_val}, R={row['density_value']}, "
                f"diff={diff}"
            )
        print(f"\npairwise_density_summand max abs diff: {max_diff:.2e}")
