"""Strict R-parity test for: dist_y

Added: 2026-03-11
Status: PASSING

R function: dist_y(y1, y2) in r_code/functions.R
Python equivalent: weatherisk.grid.dist_y

Acceptance standard (docs/python_r_parity_migration_plan.md):
    max |Python - R| < 1e-14

This is a trivial arithmetic helper (y1 - y2). Parity is exact (diff = 0).

Fixture: tests/reference_data/dist_helper_test_cases.csv
    Generated by: tests/generate_r_reference.R
    Columns: x1, x2, y1, y2, dist_x, dist_y
"""

import pandas as pd
from tests.parity.conftest import REF, STRICT_ATOL, skip_if_no_ref


class TestParityDistY:

    def setup_method(self):
        skip_if_no_ref()

    def test_dist_y_strict(self):
        """dist_y matches R to < 1e-14 on all fixture cases."""
        from weatherisk.grid import dist_y

        ref = pd.read_csv(REF / "dist_helper_test_cases.csv")
        for _, row in ref.iterrows():
            py_val = dist_y(row["y1"], row["y2"])
            r_val = row["dist_y"]
            diff = abs(py_val - r_val)
            assert diff < STRICT_ATOL, (
                f"dist_y({row['y1']}, {row['y2']}): "
                f"Python={py_val}, R={r_val}, diff={diff}"
            )
