"""Strict R-parity test for: smooth_local_estimates

Added: 2026-03-11
Status: PASSING

R function: smooth_local_estimates (smoothing logic in r_code/functions.R)
Python equivalent: weatherisk.estimation.smooth_local_estimates

Acceptance standard (docs/python_r_parity_migration_plan.md):
    max |Python - R| < 1e-14

Observed max abs diffs: a=6.22e-15, b=7.99e-15, g=4.22e-15
All within strict acceptance.

Note: The smoothing function averages over neighbouring grid cells.
For parameters a and b this is simple arithmetic averaging.
For parameter g (angle), circular averaging is used. All three
components meet the strict < 1e-14 standard against raw R fixtures.

Fixtures:
    tests/reference_data/local_estimates_all.csv — raw (unsmoothed) estimates
    tests/reference_data/local_estimates_smoothed.csv — R smoothed output
    tests/reference_data/scalar_parameters.csv — contains smoothing_dist
    Generated by: tests/generate_r_reference.R
"""

import numpy as np
import pandas as pd
from tests.parity.conftest import REF, STRICT_ATOL, skip_if_no_ref, r_to_py_index_map


class TestParitySmoothLocalEstimates:

    def setup_method(self):
        skip_if_no_ref()
        from weatherisk.grid import Grid

        self.grid = Grid(resolution=10)
        self.mapping = r_to_py_index_map(self.grid)

    def test_smooth_local_estimates_strict(self):
        """smooth_local_estimates matches R to < 1e-14 for a, b, and g."""
        from weatherisk.estimation import smooth_local_estimates

        ref_raw = pd.read_csv(REF / "local_estimates_all.csv")
        ref_smooth = pd.read_csv(REF / "local_estimates_smoothed.csv")
        scalars = pd.read_csv(REF / "scalar_parameters.csv")
        smoothing_dist = int(
            scalars.loc[scalars["parameter"] == "smoothing_dist", "value"].iloc[0]
        )

        n = self.grid.n_grid
        mapping = self.mapping

        # Map raw estimates from R order to Python order
        py_raw = np.zeros((n, 3))
        for r_idx in range(n):
            py_idx = mapping[r_idx]
            py_raw[py_idx, 0] = ref_raw.iloc[r_idx]["a_est"]
            py_raw[py_idx, 1] = ref_raw.iloc[r_idx]["b_est"]
            py_raw[py_idx, 2] = ref_raw.iloc[r_idx]["g_est"]

        py_smooth = smooth_local_estimates(
            py_raw, smoothing_dist=smoothing_dist, grid=self.grid
        )

        # Map expected smoothed values from R order to Python order
        expected = np.zeros((n, 3))
        for r_idx in range(n):
            py_idx = mapping[r_idx]
            expected[py_idx, 0] = ref_smooth.iloc[r_idx]["a_sm"]
            expected[py_idx, 1] = ref_smooth.iloc[r_idx]["b_sm"]
            expected[py_idx, 2] = ref_smooth.iloc[r_idx]["g_sm"]

        max_diff_a = np.max(np.abs(py_smooth[:, 0] - expected[:, 0]))
        max_diff_b = np.max(np.abs(py_smooth[:, 1] - expected[:, 1]))
        max_diff_g = np.max(np.abs(py_smooth[:, 2] - expected[:, 2]))

        assert max_diff_a < STRICT_ATOL, (
            f"smooth_local_estimates 'a': max abs diff = {max_diff_a:.2e}"
        )
        assert max_diff_b < STRICT_ATOL, (
            f"smooth_local_estimates 'b': max abs diff = {max_diff_b:.2e}"
        )
        assert max_diff_g < STRICT_ATOL, (
            f"smooth_local_estimates 'g': max abs diff = {max_diff_g:.2e}"
        )

        print(
            f"\nsmooth_local_estimates max abs diffs: "
            f"a={max_diff_a:.2e}, b={max_diff_b:.2e}, g={max_diff_g:.2e}"
        )
