"""Strict R-parity test for: calc_estimates_in_clusters

Added: 2026-03-11
Status: FAILING — no raw R fixtures exist

R function: calc_estimates_in_clusters (re-estimation within clusters)
            in r_code/functions.R
Python equivalent: weatherisk.estimation.calc_estimates_in_clusters

Acceptance standard (docs/python_r_parity_migration_plan.md):
    Exact selected-output matching (same optimizer contract as
    pairwise_density_optim_local, but applied within each cluster).

Current status:
    A1 (Python equivalent exists): true
    A2 (Raw R fixtures exist):     FALSE — no fixtures generated yet
    A3 (Strict tests pass):        FALSE — cannot test without fixtures

Decision (2026-03-11): This test is a placeholder. Before it can be
meaningful, raw R fixtures must be generated by extending
tests/generate_r_reference.R to run calc_estimates_in_clusters on
the frozen simulation data and cluster assignments, saving the
per-cluster re-estimated (a, b, g) parameters.

Next steps:
    1. Add fixture generation for calc_estimates_in_clusters to
       tests/generate_r_reference.R
    2. Implement strict test comparing Python output to R fixture
    3. Fix any discrepancies in the Python implementation

Fixture: NOT YET GENERATED
    Expected: tests/reference_data/calc_estimates_in_clusters_*.csv
"""

import numpy as np
import pandas as pd
from tests.parity.conftest import REF, STRICT_ATOL, skip_if_no_ref


class TestParityCalcEstimatesInClusters:

    def setup_method(self):
        skip_if_no_ref()

    def test_calc_estimates_in_clusters_strict(self):
        """calc_estimates_in_clusters matches R for LEC clusters."""
        from weatherisk.estimation import calc_estimates_in_clusters
        from weatherisk.grid import Grid

        grid = Grid(resolution=10)
        ref_clusters = pd.read_csv(REF / "clusters_lec.csv")
        ref_results = pd.read_csv(REF / "calc_estimates_in_clusters_lec.csv")

        # Read simulation data from binary to avoid R vs Python CSV parser
        # differences (1-ULP disagreements on ~26% of values)
        n_sim = 10
        sim_flat = np.fromfile(
            REF / "simulation_nonstat_seed42.bin", dtype=np.float64
        ).reshape(n_sim, grid.n_grid).T  # (n_grid, n_sim)
        sim_3d = np.zeros((grid.nrow, grid.ncol, n_sim))
        for r_idx in range(grid.n_grid):
            r_i = r_idx % grid.nrow
            r_j = r_idx // grid.nrow
            sim_3d[r_i, r_j, :] = sim_flat[r_idx, :]

        clusters = ref_clusters["cluster"].values.astype(int)
        py_results = calc_estimates_in_clusters(
            sim_3d,
            clusters,
            5.0,
            1.0,
            grid,
            cluster_ids=list(ref_results["cluster"].astype(int)),
            upper_bounds=(7.0, 10.0),
        )

        max_diff = 0.0
        for _, row in ref_results.iterrows():
            cl = int(row["cluster"])
            expected = np.array([row["a"], row["b"], row["g"], row["n_cells"], row["avg_llh"]])
            actual = py_results[cl]
            # Skip clusters where all expected values are -Inf (< 5 cells)
            if np.all(np.isneginf(expected)):
                assert np.all(np.isneginf(actual)), (
                    f"cluster {cl}: expected all -Inf but got {actual}"
                )
                continue
            diff = np.max(np.abs(actual - expected))
            max_diff = max(max_diff, diff)

        assert max_diff < STRICT_ATOL, (
            f"calc_estimates_in_clusters: max abs diff = {max_diff:.2e}"
        )
