"""Strict R-parity test for: cov_to_ec

Added: 2026-03-11
Status: PASSING

R function: cov_to_ec(df, cov) in r_code/functions.R
Python equivalent: weatherisk.covariance.cov_to_ec

Acceptance standard (docs/python_r_parity_migration_plan.md):
    max |Python - R| < 1e-14

Observed max abs diff: 5.11e-15 (within acceptance).

Fixture: tests/reference_data/cov_to_ec_test_cases.csv
    Generated by: tests/generate_r_reference.R
    Columns: df, cov, ec
"""

import pandas as pd
from tests.parity.conftest import REF, STRICT_ATOL, skip_if_no_ref


class TestParityCovToEc:

    def setup_method(self):
        skip_if_no_ref()

    def test_cov_to_ec_strict(self):
        """cov_to_ec matches R to < 1e-14 on all fixture cases."""
        from weatherisk.covariance import cov_to_ec

        ref = pd.read_csv(REF / "cov_to_ec_test_cases.csv")
        max_diff = 0.0
        for _, row in ref.iterrows():
            py_val = cov_to_ec(row["df"], row["cov"])
            diff = abs(py_val - row["ec"])
            max_diff = max(max_diff, diff)
            assert diff < STRICT_ATOL, (
                f"cov_to_ec(df={row['df']}, cov={row['cov']}): "
                f"Python={py_val}, R={row['ec']}, diff={diff}"
            )
        print(f"\ncov_to_ec max abs diff: {max_diff:.2e}")
