"""Strict R-parity test for: ec_to_cov

Added: 2026-03-11
Status: PASSING (functional parity — Python is MORE precise than R)

R function: ec_to_cov (inverse of cov_to_ec via uniroot) in r_code/functions.R
Python equivalent: weatherisk.covariance.ec_to_cov

Acceptance standard (docs/python_r_parity_migration_plan.md):
    Functional parity: |cov_to_ec(df, py_root) - target_ec| < 1e-14

Why not direct root comparison:
    ec_to_cov is a root-finding inverse: given target ec, find cov such that
    cov_to_ec(df, cov) == ec. R uses uniroot with default tolerance
    .Machine$double.eps^0.25 ≈ 1.22e-04 — a deliberately LOOSE tolerance.
    Python uses scipy.optimize.brentq with xtol=1e-15.

    As a result, Python finds roots that are strictly MORE accurate than R:
      - R's root for ec_to_cov(1, 1.1): cov=0.979974092322653
        → cov_to_ec(1, 0.979974...) = 1.10006..., function error = 6.47e-05
      - Python's root: cov≈0.98
        → cov_to_ec(1, 0.98) = 1.1, function error ≈ 0

    The root values differ by ~2.59e-05, but this is NOT an error in Python —
    it is an improvement. Python's root satisfies the defining equation
    cov_to_ec(df, cov) == ec to machine precision, while R's does not.

    We therefore test functional parity: the forward-evaluated result
    cov_to_ec(df, py_root) must match the target ec to < 1e-14. This is
    the mathematically correct acceptance criterion for an inverse function.

    No R subprocess dependency. No dependency on R at all.

Fixture: tests/reference_data/ec_to_cov_test_cases.csv
    Generated by: tests/generate_r_reference.R
    Columns: df, ec, cov
"""

import pandas as pd
from tests.parity.conftest import REF, STRICT_ATOL, skip_if_no_ref


class TestParityEcToCov:

    def setup_method(self):
        skip_if_no_ref()

    def test_ec_to_cov_functional_parity(self):
        """ec_to_cov: cov_to_ec(df, py_root) matches target ec to < 1e-14.

        This tests that Python's root is functionally correct: when we
        feed py_root back through the forward function cov_to_ec, we
        recover the target ec to machine precision.

        Python's brentq(xtol=1e-15) finds a MORE accurate root than
        R's uniroot (tolerance ≈ 1.22e-04), so direct root comparison
        would fail at ~2.59e-05 even though Python is strictly better.
        """
        from weatherisk.covariance import cov_to_ec, ec_to_cov

        ref = pd.read_csv(REF / "ec_to_cov_test_cases.csv")
        max_func_diff = 0.0
        max_root_diff = 0.0
        r_max_func_err = 0.0
        for _, row in ref.iterrows():
            df, target_ec, r_root = row["df"], row["ec"], row["cov"]
            py_root = ec_to_cov(df, target_ec)

            # ec_to_cov clamps ec to min(ec, cov_to_ec(df, 0.0)) before
            # solving, so the effective target for boundary cases differs
            # from the input.  Compare against the clamped value.
            clamped_ec = min(target_ec, cov_to_ec(df, 0.0))

            # Functional parity: does py_root satisfy the defining equation?
            py_forward = cov_to_ec(df, py_root)
            func_diff = abs(py_forward - clamped_ec)
            max_func_diff = max(max_func_diff, func_diff)

            # Track root difference (informational, not part of acceptance)
            root_diff = abs(py_root - r_root)
            max_root_diff = max(max_root_diff, root_diff)

            # Track R's own functional error (informational)
            r_forward = cov_to_ec(df, r_root)
            r_func_err = abs(r_forward - clamped_ec)
            r_max_func_err = max(r_max_func_err, r_func_err)

            assert func_diff < STRICT_ATOL, (
                f"ec_to_cov(df={df}, ec={target_ec}): "
                f"cov_to_ec(df, py_root={py_root}) = {py_forward}, "
                f"clamped_ec={clamped_ec}, diff = {func_diff}"
            )

        print(f"\nec_to_cov functional parity:")
        print(f"  Python max |cov_to_ec(df, py_root) - ec|: {max_func_diff:.2e}")
        print(f"  R max |cov_to_ec(df, r_root) - ec|:       {r_max_func_err:.2e}")
        print(f"  Max |py_root - r_root|:                    {max_root_diff:.2e}")
        print(f"  → Python is MORE precise than R")
