"""Strict R-parity test for: cluster_number_threshold_method

Added: 2026-03-11
Status: FAILING

R function: cluster_number_threshold_method in r_code/functions.R
Python equivalent: weatherisk.clustering.cluster_number_threshold_method

Acceptance standard (docs/python_r_parity_migration_plan.md):
    Exact raw-R cluster count matching for both LEC and Saunders.

Current status:
    LEC cluster count:     matches raw R (k=22)
    Saunders cluster count: differs by +1 from raw R

Decision (2026-03-11): This function cannot be accepted independently
while the upstream clustering function (merge heights) still fails
strict parity. Even if the cluster count happens to match on the LEC
fixture, the chain from distance matrix → merge heights → cluster count
must all be correct under the strict contract. Since clustering merge
heights fail strict parity (especially Saunders), this function is
marked as failing.

Note: The legacy test in test_r_cross_validation.py allows ±1 for
Saunders, which does not count for strict acceptance.

Fixtures:
    tests/reference_data/lec_clustering_params.csv — k_lec, q10_threshold
    tests/reference_data/saunders_clustering_params.csv — k_saunders, q30_threshold
    tests/reference_data/ellipse_dissimilarity_matrix.csv — LEC distance input
    tests/reference_data/madogram_matrix.csv — Saunders distance input
    Generated by: tests/generate_r_reference.R
"""

import pytest
import pandas as pd
from tests.parity.conftest import REF, skip_if_no_ref


class TestParityClusterNumberThresholdMethod:

    def setup_method(self):
        skip_if_no_ref()

    def test_lec_and_saunders_cluster_count_strict(self):
        """Cluster counts for both LEC and Saunders match R exactly."""
        from weatherisk.clustering import clustering, cluster_number_threshold_method

        # LEC
        lec_params = pd.read_csv(REF / "lec_clustering_params.csv")
        k_lec_r = int(lec_params["k_lec"].iloc[0])
        q10 = float(lec_params["q10_threshold"].iloc[0])

        lec_dist = pd.read_csv(REF / "ellipse_dissimilarity_matrix.csv").values
        hc_lec = clustering(lec_dist, method="average")
        k_lec_py = cluster_number_threshold_method(hc_lec, q10)

        # Saunders
        saund_params = pd.read_csv(REF / "saunders_clustering_params.csv")
        k_saund_r = int(saund_params["k_saunders"].iloc[0])
        q30 = float(saund_params["q30_threshold"].iloc[0])

        saund_dist = pd.read_csv(REF / "madogram_matrix.csv").values
        hc_saund = clustering(saund_dist, method="average")
        k_saund_py = cluster_number_threshold_method(hc_saund, q30)

        assert k_lec_py == k_lec_r, (
            f"LEC cluster count: Python={k_lec_py}, R={k_lec_r}"
        )
        assert k_saund_py == k_saund_r, (
            f"Saunders cluster count: Python={k_saund_py}, R={k_saund_r}"
        )
