"""Strict R-parity test for: number_grid

Added: 2026-03-11
Status: PASSING

R function: number_grid(n) in r_code/functions.R
Python equivalent: weatherisk.grid.Grid.number_grid

Acceptance standard (docs/python_r_parity_migration_plan.md):
    Exact integer equality after documented 0-based normalization.

R uses 1-based indices. Python uses 0-based. The test verifies:
    py_number_grid(r_n - 1) == (r_i - 1, r_j - 1)

Fixture: tests/reference_data/number_grid_test_cases.csv
    Generated by: tests/generate_r_reference.R
    Columns: n, i, j (all 1-based in R)
"""

import pandas as pd
from tests.parity.conftest import REF, skip_if_no_ref


class TestParityNumberGrid:

    def setup_method(self):
        skip_if_no_ref()
        from weatherisk.grid import Grid

        self.grid = Grid(resolution=10)

    def test_number_grid_strict(self):
        """number_grid matches R exactly (after 0/1-based normalization)."""
        ref = pd.read_csv(REF / "number_grid_test_cases.csv")
        for _, row in ref.iterrows():
            r_n = int(row["n"])
            r_i, r_j = int(row["i"]), int(row["j"])
            py_i, py_j = self.grid.number_grid(r_n - 1)
            assert py_i == r_i - 1, (
                f"number_grid({r_n - 1})[0]: Python={py_i}, expected={r_i - 1}"
            )
            assert py_j == r_j - 1, (
                f"number_grid({r_n - 1})[1]: Python={py_j}, expected={r_j - 1}"
            )
