"""Strict R-parity test for: calc_distance_ellipses

Added: 2026-03-11
Status: FAILING

R function: calc_distance_ellipses in r_code/functions.R
Python equivalent: weatherisk.clustering.calc_distance_ellipses

Acceptance standard (docs/python_r_parity_migration_plan.md):
    max |Python - R| < 1e-14

Current observed max abs diff vs raw R: 5.68e-14 (just outside 1e-14).

This function computes pairwise ellipse dissimilarity (1 - IoU) scaled
to 0-100. The raw R fixture uses R's historical linear-indexing behavior.

Decision (2026-03-11): Strict parity means matching the RAW R output
from the historical code, including any indexing bugs that affect the
numerical output. Whether this is scientifically desirable is a separate
question documented in the migration plan under "calc_distance_ellipses."

Note: The legacy test in test_r_cross_validation.py uses atol=0.5,
which does not count for strict acceptance.

Fixture: tests/reference_data/ellipse_dissimilarity_matrix.csv
    Raw R output of calc_distance_ellipses on smoothed local estimates.
    Generated by: tests/generate_r_reference.R
Fixture: tests/reference_data/local_estimates_smoothed.csv
    Smoothed estimates used as input (R column-major order).
"""

import numpy as np
import pandas as pd
from tests.parity.conftest import REF, skip_if_no_ref, r_to_py_index_map

CSV_ATOL = 5e-14


class TestParityCalcDistanceEllipses:

    def setup_method(self):
        skip_if_no_ref()
        from weatherisk.grid import Grid

        self.grid = Grid(resolution=10)
        self.mapping = r_to_py_index_map(self.grid)

    def test_ellipse_dissimilarity_strict(self):
        """calc_distance_ellipses matches raw R to CSV precision."""
        from weatherisk.clustering import calc_distance_ellipses

        ref_dist = pd.read_csv(REF / "ellipse_dissimilarity_matrix.csv").values
        ref_smooth = pd.read_csv(REF / "local_estimates_smoothed.csv")
        n = self.grid.n_grid
        mapping = self.mapping

        # Build smoothed estimates in Python's flat order
        py_estimates = np.zeros((n, 3))
        for r_idx in range(n):
            py_idx = mapping[r_idx]
            py_estimates[py_idx, 0] = ref_smooth.iloc[r_idx]["a_sm"]
            py_estimates[py_idx, 1] = ref_smooth.iloc[r_idx]["b_sm"]
            py_estimates[py_idx, 2] = ref_smooth.iloc[r_idx]["g_sm"]

        py_dist = calc_distance_ellipses(py_estimates, res=21)

        # Re-index reference from R column-major to Python row-major
        ref_reindexed = np.zeros_like(ref_dist)
        for r_i in range(n):
            for r_j in range(n):
                ref_reindexed[mapping[r_i], mapping[r_j]] = ref_dist[r_i, r_j]

        max_diff = np.max(np.abs(py_dist - ref_reindexed))
        assert max_diff < CSV_ATOL, (
            f"calc_distance_ellipses: max abs diff = {max_diff:.2e}"
        )
        print(f"\ncalc_distance_ellipses max abs diff: {max_diff:.2e}")
