"""Strict R-parity test for: c_extrcoeff_matrix

Added: 2026-03-11
Status: PASSING

R function: c_extrcoeff_matrix(sim_all, madogram) in r_code/functions.R
Python equivalent: weatherisk.clustering.c_extrcoeff_matrix

Acceptance standard (docs/python_r_parity_migration_plan.md):
    max |Python - R| < 1e-14

Observed max abs diffs: madogram mode = 4.72e-16, EC mode = 4.99e-16.
Both well within strict acceptance.

Note: The simulation data must be reshaped from R's column-major flat
ordering to Python's (nrow, ncol, n_sim) array. The output matrices
are re-indexed from R's column-major ordering to Python's row-major
ordering via coordinate matching before comparison.

Fixtures:
    tests/reference_data/simulation_nonstat_seed42.csv — simulation data
    tests/reference_data/madogram_matrix.csv — R madogram output
    tests/reference_data/extremal_coefficient_matrix.csv — R EC output
    Generated by: tests/generate_r_reference.R
"""

import numpy as np
import pandas as pd
from tests.parity.conftest import REF, STRICT_ATOL, skip_if_no_ref, r_to_py_index_map


class TestParityCExtrcoeffMatrix:

    def setup_method(self):
        skip_if_no_ref()
        from weatherisk.grid import Grid

        self.grid = Grid(resolution=10)
        self.mapping = r_to_py_index_map(self.grid)

        # Load R simulation data
        sim_ref = pd.read_csv(REF / "simulation_nonstat_seed42.csv")
        sim_cols = [c for c in sim_ref.columns if c.startswith("sim")]
        self.n_sim = len(sim_cols)
        n = self.grid.n_grid

        # Reshape to 3D: (nrow, ncol, n_sim), mapping from R column-major
        self.sim_3d = np.zeros((self.grid.nrow, self.grid.ncol, self.n_sim))
        for r_idx in range(n):
            r_i = r_idx % self.grid.nrow
            r_j = r_idx // self.grid.nrow
            for k, col in enumerate(sim_cols):
                self.sim_3d[r_i, r_j, k] = sim_ref[col].iloc[r_idx]

    def _reindex_matrix(self, ref_matrix):
        """Re-index an n x n matrix from R column-major to Python row-major."""
        n = self.grid.n_grid
        mapping = self.mapping
        reindexed = np.zeros_like(ref_matrix)
        for r_i in range(n):
            for r_j in range(n):
                reindexed[mapping[r_i], mapping[r_j]] = ref_matrix[r_i, r_j]
        return reindexed

    def test_madogram_matrix_strict(self):
        """c_extrcoeff_matrix(madogram=True) matches R to < 1e-14."""
        from weatherisk.clustering import c_extrcoeff_matrix

        ref_mado = pd.read_csv(REF / "madogram_matrix.csv").values
        py_mado = c_extrcoeff_matrix(self.sim_3d, madogram=True)
        ref_reindexed = self._reindex_matrix(ref_mado)

        max_diff = np.max(np.abs(py_mado - ref_reindexed))
        assert max_diff < STRICT_ATOL, (
            f"c_extrcoeff_matrix(madogram=True): max abs diff = {max_diff:.2e}"
        )
        print(f"\nc_extrcoeff_matrix madogram max abs diff: {max_diff:.2e}")

    def test_extremal_coefficient_matrix_strict(self):
        """c_extrcoeff_matrix(madogram=False) matches R to < 1e-14."""
        from weatherisk.clustering import c_extrcoeff_matrix

        ref_ec = pd.read_csv(REF / "extremal_coefficient_matrix.csv").values
        py_ec = c_extrcoeff_matrix(self.sim_3d, madogram=False)
        ref_reindexed = self._reindex_matrix(ref_ec)

        max_diff = np.max(np.abs(py_ec - ref_reindexed))
        assert max_diff < STRICT_ATOL, (
            f"c_extrcoeff_matrix(madogram=False): max abs diff = {max_diff:.2e}"
        )
        print(f"\nc_extrcoeff_matrix EC max abs diff: {max_diff:.2e}")
