"""Strict R-parity test for: grid_number

Added: 2026-03-11
Status: PASSING

R function: grid_number(i, j) in r_code/functions.R
Python equivalent: weatherisk.grid.Grid.grid_number

Acceptance standard (docs/python_r_parity_migration_plan.md):
    Exact integer equality after documented 0-based normalization.

R uses 1-based indices (both for i, j inputs and the returned flat index).
Python uses 0-based indices. The test verifies:
    py_grid_number(r_i - 1, r_j - 1) == r_result - 1

Fixture: tests/reference_data/grid_number_test_cases.csv
    Generated by: tests/generate_r_reference.R
    Columns: i, j, grid_num (all 1-based in R)
"""

import pandas as pd
from tests.parity.conftest import REF, skip_if_no_ref


class TestParityGridNumber:

    def setup_method(self):
        skip_if_no_ref()
        from weatherisk.grid import Grid

        self.grid = Grid(resolution=10)

    def test_grid_number_strict(self):
        """grid_number matches R exactly (after 0/1-based normalization)."""
        ref = pd.read_csv(REF / "grid_number_test_cases.csv")
        for _, row in ref.iterrows():
            r_i, r_j = int(row["i"]), int(row["j"])
            r_n = int(row["grid_num"])
            py_n = self.grid.grid_number(r_i - 1, r_j - 1)
            assert py_n == r_n - 1, (
                f"grid_number({r_i - 1}, {r_j - 1}): "
                f"Python={py_n}, expected={r_n - 1} (R={r_n})"
            )
