"""Strict R-parity test for: pairwise_density_optim_local

Added: 2026-03-11
Status: FAILING

R function: pairwise_density_optim_local in r_code/functions.R
Python equivalent: weatherisk.density.pairwise_density_optim_local

Acceptance standard (docs/python_r_parity_migration_plan.md):
    Exact selected-output matching. The optimizer must return the same
    (a, b, g) parameters as R for the same frozen inputs.

Current observed max abs diff on selected outputs: 7.24e-01.
This is a large discrepancy indicating fundamental differences in
optimizer behavior (start generation, L-BFGS-B implementation,
branch selection logic).

The parity contract for optimizer functions is stricter than a simple
tolerance check: the full selected-result contract must match exactly,
including starting design, retries, branch selection, and returned
parameters.

Fixtures:
    tests/reference_data/local_estimates_selected_points.csv
        Per-grid-point selected optimizer outputs from R.
        Columns: grid_point, X, Y, a_est, b_est, g_est, a_true, b_true, g_true
    tests/reference_data/local_optimizer_min_inputs.csv
        Pairwise z/coordinate inputs for each grid point.
    tests/reference_data/local_optimizer_min_outputs.csv
        Per-grid-point optimizer bounds and returned values.
    Generated by: tests/generate_r_reference.R
"""

import numpy as np
import pandas as pd
from tests.parity.conftest import REF, STRICT_ATOL, skip_if_no_ref


class TestParityPairwiseDensityOptimLocal:

    def setup_method(self):
        skip_if_no_ref()

    def test_selected_outputs_strict(self):
        """Optimizer returns same (a, b, g) as R for each selected point.

        Uses frozen pair arrays from the R fixture to eliminate any
        pair-construction differences. This tests the R subprocess
        optimizer bridge at the raw input level.
        """
        from weatherisk.backend import optimize_local_mle

        ref_outputs = pd.read_csv(REF / "local_optimizer_selected_outputs.csv")

        # Read pair arrays from binary to avoid R vs Python CSV parser
        # differences (1-ULP disagreements on ~26% of values)
        bin_path = REF / "local_optimizer_selected_inputs.bin"
        with open(bin_path, "rb") as f:
            n_rows = int(np.frombuffer(f.read(4), dtype=np.int32)[0])
            grid_points = np.frombuffer(f.read(n_rows * 8), dtype=np.float64)
            zi_all = np.frombuffer(f.read(n_rows * 8), dtype=np.float64)
            zj_all = np.frombuffer(f.read(n_rows * 8), dtype=np.float64)
            xl_all = np.frombuffer(f.read(n_rows * 8), dtype=np.float64)
            yl_all = np.frombuffer(f.read(n_rows * 8), dtype=np.float64)

        scalars = pd.read_csv(REF / "scalar_parameters.csv")
        ensemble = int(
            scalars.loc[scalars["parameter"] == "locest_ensemble", "value"].iloc[0]
        )

        max_diff = 0.0
        for _, row in ref_outputs.iterrows():
            gp = int(row["grid_point"])
            mask = grid_points == gp
            zi = zi_all[mask]
            zj = zj_all[mask]
            xl = xl_all[mask]
            yl = yl_all[mask]

            py_result = optimize_local_mle(
                zi, zj, xl, yl,
                df=5.0,
                alpha=1.0,
                ensemble=ensemble,
                seed=42,
                max_boundary_retries=5,
                lower_bounds=(float(row["lower_a"]), float(row["lower_b"])),
                upper_bounds=(float(row["upper_a"]), float(row["upper_b"])),
            )
            r_result = np.array([row["a_est"], row["b_est"], row["g_est"]])
            diff = np.max(np.abs(py_result - r_result))
            max_diff = max(max_diff, diff)

        assert max_diff < STRICT_ATOL, (
            f"pairwise_density_optim_local: max abs diff = {max_diff:.2e}"
        )
        print(
            f"\npairwise_density_optim_local max abs diff: {max_diff:.2e}"
        )
