"""Strict R-parity test for: koord_num

Added: 2026-03-11
Status: PASSING

R function: koord_num(x, y) in r_code/functions.R
Python equivalent: weatherisk.grid.Grid.koord_num

Acceptance standard (docs/python_r_parity_migration_plan.md):
    Coordinate-equivalent fixture confirms the same selected grid point
    as R under normalized indexing conventions.

koord_num returns the flat index of the nearest grid point to (x, y).
R and Python may return different flat indices (due to R being 1-based
column-major and Python being 0-based row-major), but the COORDINATES
of the selected grid point must be identical.

Fixture: tests/reference_data/koord_num_test_cases.csv
    Generated by: tests/generate_r_reference.R
    Columns: x, y, Xval, Yval (coordinates of the selected grid point in R)
"""

import pandas as pd
from tests.parity.conftest import REF, STRICT_ATOL, skip_if_no_ref


class TestParityKoordNum:

    def setup_method(self):
        skip_if_no_ref()
        from weatherisk.grid import Grid

        self.grid = Grid(resolution=10)

    def test_koord_num_strict(self):
        """koord_num selects the same grid point coordinates as R."""
        ref = pd.read_csv(REF / "koord_num_test_cases.csv")
        for _, row in ref.iterrows():
            py_idx = self.grid.koord_num(row["x"], row["y"])
            px, py = self.grid.number_koord(py_idx)
            diff_x = abs(px - row["Xval"])
            diff_y = abs(py - row["Yval"])
            assert diff_x < STRICT_ATOL, (
                f"koord_num({row['x']}, {row['y']}): "
                f"X: Python={px}, R={row['Xval']}, diff={diff_x}"
            )
            assert diff_y < STRICT_ATOL, (
                f"koord_num({row['x']}, {row['y']}): "
                f"Y: Python={py}, R={row['Yval']}, diff={diff_y}"
            )
