"""Strict R-parity test for: cov_fkt_2d

Added: 2026-03-11
Status: PASSING

R function: cov_fkt_2d(x, y, alpha, a, b, g) in r_code/functions.R
Python equivalent: weatherisk.covariance.cov_fkt_2d

Acceptance standard (docs/python_r_parity_migration_plan.md):
    max |Python - R| < 1e-14

Observed max abs diff: 1.44e-15 (well within acceptance).

Fixture: tests/reference_data/cov_fkt_2d_test_cases.csv
    Generated by: tests/generate_r_reference.R
    Columns: x, y, alpha, a, b, g, cov_value
"""

import numpy as np
import pandas as pd
from tests.parity.conftest import REF, STRICT_ATOL, skip_if_no_ref


class TestParityCovFkt2d:

    def setup_method(self):
        skip_if_no_ref()

    def test_cov_fkt_2d_strict(self):
        """cov_fkt_2d matches R to < 1e-14 on all fixture cases."""
        from weatherisk.covariance import cov_fkt_2d

        ref = pd.read_csv(REF / "cov_fkt_2d_test_cases.csv")
        max_diff = 0.0
        for _, row in ref.iterrows():
            py_val = cov_fkt_2d(
                row["x"], row["y"],
                alpha=row["alpha"], a=row["a"], b=row["b"], g=row["g"],
            )
            diff = abs(py_val - row["cov_value"])
            max_diff = max(max_diff, diff)
            assert diff < STRICT_ATOL, (
                f"cov_fkt_2d(x={row['x']}, y={row['y']}, "
                f"a={row['a']}, b={row['b']}, g={row['g']}): "
                f"Python={py_val}, R={row['cov_value']}, diff={diff}"
            )
        # Log the observed max for documentation
        print(f"\ncov_fkt_2d max abs diff: {max_diff:.2e}")
