"""Cross-validation tests: verify Python weatherisk matches R reference outputs.

Every test loads reference CSV data generated by the R pipeline
(tests/generate_r_reference.R) and asserts that the Python implementation
produces numerically equivalent results.

The R code uses COLUMN-MAJOR (Fortran) ordering for flat indices;
Python uses ROW-MAJOR (C) ordering.  All comparisons are done by
matching on (X, Y) coordinates, not on flat indices.
"""

from __future__ import annotations

import os
from pathlib import Path

import numpy as np
import pandas as pd
import pytest
from scipy.cluster.hierarchy import fcluster
from scipy.spatial.distance import squareform

REF = Path(__file__).parent / "reference_data"


def _skip_if_no_ref():
    """Skip if reference data has not been generated."""
    if not (REF / "grid_coordinates.csv").exists():
        pytest.skip("R reference data not generated — run: Rscript tests/generate_r_reference.R")


# ---------------------------------------------------------------------------
#  Helper: build an R-index → Python-index mapping via coordinates
# ---------------------------------------------------------------------------

def _r_to_py_index_map(grid):
    """Return array m where m[r_flat_0based] = py_flat_0based.

    R flat index n (1-based, column-major) corresponds to coordinate
    (X_R[n], Y_R[n]).  Python flat index p (0-based, row-major) satisfies
    grid.X.flat[p] == X_R[n] and grid.Y.flat[p] == Y_R[n].
    """
    ref = pd.read_csv(REF / "grid_coordinates.csv")
    mapping = np.empty(len(ref), dtype=int)
    for idx, row in ref.iterrows():
        r_x, r_y = row["X"], row["Y"]
        py_idx = grid.koord_num(r_x, r_y)
        mapping[idx] = py_idx
    return mapping


# ═══════════════════════════════════════════════════════════════════════════
#  1. GRID & PARAMETERS
# ═══════════════════════════════════════════════════════════════════════════

class TestGridCoordinates:
    """Verify grid construction matches R parameters.R."""

    def setup_method(self):
        _skip_if_no_ref()
        from weatherisk.grid import Grid
        self.grid = Grid(resolution=10)

    def test_axes(self):
        ref_x = pd.read_csv(REF / "x_axis.csv")["x_ax"].values
        ref_y = pd.read_csv(REF / "y_axis.csv")["y_ax"].values
        np.testing.assert_allclose(self.grid.x_ax, ref_x, atol=1e-12)
        np.testing.assert_allclose(self.grid.y_ax, ref_y, atol=1e-12)

    def test_grid_coordinates_match_r(self):
        """Every R coordinate pair exists in the Python grid."""
        ref = pd.read_csv(REF / "grid_coordinates.csv")
        for _, row in ref.iterrows():
            py_idx = self.grid.koord_num(row["X"], row["Y"])
            px, py = self.grid.number_koord(py_idx)
            assert abs(px - row["X"]) < 1e-10
            assert abs(py - row["Y"]) < 1e-10

    def test_dist_helpers_match_r(self):
        from weatherisk.grid import dist_x, dist_y

        ref = pd.read_csv(REF / "dist_helper_test_cases.csv")
        for _, row in ref.iterrows():
            np.testing.assert_allclose(dist_x(row["x1"], row["x2"]), row["dist_x"], atol=1e-14)
            np.testing.assert_allclose(dist_y(row["y1"], row["y2"]), row["dist_y"], atol=1e-14)

    def test_grid_number_matches_r(self):
        """grid_number / number_grid round-trip (accounting for 0/1-based)."""
        ref = pd.read_csv(REF / "grid_number_test_cases.csv")
        for _, row in ref.iterrows():
            r_i, r_j = int(row["i"]), int(row["j"])
            r_n = int(row["grid_num"])
            # R is 1-based, Python 0-based
            py_n = self.grid.grid_number(r_i - 1, r_j - 1)
            assert py_n == r_n - 1

    def test_number_grid_matches_r(self):
        ref = pd.read_csv(REF / "number_grid_test_cases.csv")
        for _, row in ref.iterrows():
            r_n = int(row["n"])
            r_i, r_j = int(row["i"]), int(row["j"])
            py_i, py_j = self.grid.number_grid(r_n - 1)
            assert py_i == r_i - 1
            assert py_j == r_j - 1

    def test_koord_num_same_coordinates(self):
        """koord_num returns a point with the same coordinates as R."""
        ref = pd.read_csv(REF / "koord_num_test_cases.csv")
        for _, row in ref.iterrows():
            py_idx = self.grid.koord_num(row["x"], row["y"])
            px, py = self.grid.number_koord(py_idx)
            assert abs(px - row["Xval"]) < 1e-10
            assert abs(py - row["Yval"]) < 1e-10

    def test_parameter_matrices(self):
        """Stripes preset parameter matrices match R."""
        from weatherisk.parameters import get_preset
        preset = get_preset("stripes")
        a_py = preset.a_func(self.grid.X, self.grid.Y)
        b_py = preset.b_func(self.grid.X, self.grid.Y)
        g_py = preset.g_func(self.grid.X, self.grid.Y)

        ref = pd.read_csv(REF / "parameter_matrices.csv")
        # Compare by coordinate matching
        mapping = _r_to_py_index_map(self.grid)

        for r_idx in range(len(ref)):
            py_idx = mapping[r_idx]
            py_row, py_col = self.grid.number_grid(py_idx)
            assert abs(a_py[py_row, py_col] - ref.iloc[r_idx]["a"]) < 1e-10
            assert abs(b_py[py_row, py_col] - ref.iloc[r_idx]["b"]) < 1e-10, \
                f"b mismatch at R index {r_idx}: py={b_py[py_row, py_col]}, R={ref.iloc[r_idx]['b']}"
            assert abs(g_py[py_row, py_col] - ref.iloc[r_idx]["g"]) < 1e-10


# ═══════════════════════════════════════════════════════════════════════════
#  2. COVARIANCE FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════

class TestCovarianceFunctions:
    """Verify cov_fkt_2d matches R to machine precision."""

    def setup_method(self):
        _skip_if_no_ref()

    def test_cov_fkt_2d(self):
        from weatherisk.covariance import cov_fkt_2d
        ref = pd.read_csv(REF / "cov_fkt_2d_test_cases.csv")
        for _, row in ref.iterrows():
            py_val = cov_fkt_2d(row["x"], row["y"],
                                alpha=row["alpha"], a=row["a"],
                                b=row["b"], g=row["g"])
            np.testing.assert_allclose(
                py_val, row["cov_value"], atol=1e-12, rtol=1e-12,
                err_msg=f"cov_fkt_2d({row['x']},{row['y']},a={row['a']},b={row['b']},g={row['g']})"
            )

    def test_cov_fkt_2d_alpha_variants(self):
        from weatherisk.covariance import cov_fkt_2d
        ref = pd.read_csv(REF / "cov_fkt_2d_alpha_cases.csv")
        for _, row in ref.iterrows():
            py_val = cov_fkt_2d(row["x"], row["y"],
                                alpha=row["alpha"], a=row["a"],
                                b=row["b"], g=row["g"])
            np.testing.assert_allclose(
                py_val, row["cov_value"], atol=1e-12, rtol=1e-12,
                err_msg=f"alpha={row['alpha']}, a={row['a']}, b={row['b']}, g={row['g']}"
            )

    def test_cov_fkt_2d_nonstat(self):
        from weatherisk.covariance import cov_fkt_2d_nonstat2
        ref = pd.read_csv(REF / "cov_nonstat_test_cases.csv")
        for _, row in ref.iterrows():
            py_val = cov_fkt_2d_nonstat2(
                row["x"], row["y"], alpha=row["alpha"],
                a1=row["a1"], b1=row["b1"], g1=row["g1"],
                a2=row["a2"], b2=row["b2"], g2=row["g2"],
            )
            np.testing.assert_allclose(
                py_val, row["cov_value"], atol=1e-10, rtol=1e-10,
                err_msg=f"nonstat: x={row['x']}, y={row['y']}"
            )


# ═══════════════════════════════════════════════════════════════════════════
#  3. EXTREMAL COEFFICIENT CONVERSION
# ═══════════════════════════════════════════════════════════════════════════

class TestExtremalCoeffConversion:
    """Verify cov_to_ec and ec_to_cov match R."""

    def setup_method(self):
        _skip_if_no_ref()

    def test_cov_to_ec(self):
        from weatherisk.covariance import cov_to_ec
        ref = pd.read_csv(REF / "cov_to_ec_test_cases.csv")
        for _, row in ref.iterrows():
            py_val = cov_to_ec(row["df"], row["cov"])
            np.testing.assert_allclose(
                py_val, row["ec"], atol=1e-10,
                err_msg=f"cov_to_ec(df={row['df']}, cov={row['cov']})"
            )

    def test_ec_to_cov(self):
        from weatherisk.covariance import ec_to_cov
        ref = pd.read_csv(REF / "ec_to_cov_test_cases.csv")
        for _, row in ref.iterrows():
            py_val = ec_to_cov(row["df"], row["ec"])
            np.testing.assert_allclose(
                py_val, row["cov"], atol=1e-14,
                err_msg=f"ec_to_cov(df={row['df']}, ec={row['ec']})"
            )


# ═══════════════════════════════════════════════════════════════════════════
#  4. PAIRWISE DENSITY SUMMAND
# ═══════════════════════════════════════════════════════════════════════════

class TestPairwiseDensity:
    """Verify the pairwise composite likelihood density against R."""

    def setup_method(self):
        _skip_if_no_ref()

    def test_dtdiff(self):
        from weatherisk.density import _dtdiff
        ref = pd.read_csv(REF / "dtdiff_test_cases.csv")
        for _, row in ref.iterrows():
            py_val = _dtdiff(row["x"], row["df"])
            np.testing.assert_allclose(
                py_val, row["dtdiff_value"], atol=1e-12,
                err_msg=f"dtdiff({row['x']}, {row['df']})"
            )

    def test_pairwise_density_summand(self):
        from weatherisk.density import pairwise_density_summand
        ref = pd.read_csv(REF / "pairwise_density_test_cases.csv")
        for _, row in ref.iterrows():
            py_val = pairwise_density_summand(
                row["z1"], row["z2"], row["x"], row["y"],
                row["df"], row["alpha"], row["a"], row["b"], row["g"],
            )
            np.testing.assert_allclose(
                py_val, row["density_value"], atol=1e-8, rtol=1e-8,
                err_msg=(f"summand(z1={row['z1']},z2={row['z2']},"
                         f"x={row['x']},y={row['y']},"
                         f"a={row['a']},b={row['b']},g={row['g']})")
            )


# ═══════════════════════════════════════════════════════════════════════════
#  5. COVARIANCE MATRICES
# ═══════════════════════════════════════════════════════════════════════════

class TestCovarianceMatrices:
    """Verify full n×n covariance matrices match R."""

    def setup_method(self):
        _skip_if_no_ref()
        from weatherisk.grid import Grid
        self.grid = Grid(resolution=10)
        self.mapping = _r_to_py_index_map(self.grid)

    def test_stationary_covariance_matrix(self):
        from weatherisk.covariance import cov_fkt_2d
        ref = pd.read_csv(REF / "covariance_matrix_stationary.csv").values
        n = self.grid.n_grid
        assert ref.shape == (n, n)

        # Build Python matrix using Fortran-order coordinates to match R
        X_f = self.grid.X.flatten('F')
        Y_f = self.grid.Y.flatten('F')
        py_cov = np.zeros((n, n))
        for i in range(n):
            for j in range(n):
                py_cov[i, j] = cov_fkt_2d(
                    X_f[i] - X_f[j], Y_f[i] - Y_f[j],
                    alpha=1.0, a=2.0, b=1.0, g=0.0
                )
        np.testing.assert_allclose(py_cov, ref, atol=1e-12)

    def test_nonstationary_covariance_matrix(self):
        from weatherisk.covariance import cov_fkt_2d_nonstat2
        from weatherisk.parameters import get_preset
        ref = pd.read_csv(REF / "covariance_matrix_nonstationary.csv").values
        preset = get_preset("stripes")
        n = self.grid.n_grid

        a_mat = preset.a_func(self.grid.X, self.grid.Y)
        b_mat = preset.b_func(self.grid.X, self.grid.Y)
        g_mat = preset.g_func(self.grid.X, self.grid.Y)

        # Flatten in Fortran order to match R
        X_f = self.grid.X.flatten('F')
        Y_f = self.grid.Y.flatten('F')
        a_f = a_mat.flatten('F')
        b_f = b_mat.flatten('F')
        g_f = g_mat.flatten('F')

        py_cov = np.zeros((n, n))
        for i in range(n):
            for j in range(n):
                py_cov[i, j] = cov_fkt_2d_nonstat2(
                    X_f[i] - X_f[j], Y_f[i] - Y_f[j], alpha=1.0,
                    a1=a_f[i], b1=b_f[i], g1=g_f[i],
                    a2=a_f[j], b2=b_f[j], g2=g_f[j],
                )
        np.testing.assert_allclose(py_cov, ref, atol=1e-10)


# ═══════════════════════════════════════════════════════════════════════════
#  6. MADOGRAM / EXTREMAL COEFFICIENT MATRIX
# ═══════════════════════════════════════════════════════════════════════════

class TestMadogramMatrix:
    """Verify madogram and extremal coefficient matrices match R."""

    def setup_method(self):
        _skip_if_no_ref()
        from weatherisk.grid import Grid
        self.grid = Grid(resolution=10)
        self.mapping = _r_to_py_index_map(self.grid)
        # Load R simulation data and reshape to (10,10,10) in R order
        sim_ref = pd.read_csv(REF / "simulation_nonstat_seed42.csv")
        sim_cols = [c for c in sim_ref.columns if c.startswith("sim")]
        self.n_sim = len(sim_cols)
        # Build 3D array in R's column-major grid order
        # R: sim_all[i,j,k] where i=row, j=col of 10x10 grid
        # flat_index in R is column-major: (i,j) -> (j-1)*nrow + i
        n = self.grid.n_grid
        self.sim_data_r_order = np.zeros((n, self.n_sim))
        for k, col in enumerate(sim_cols):
            self.sim_data_r_order[:, k] = sim_ref[col].values

    def test_madogram_matrix(self):
        from weatherisk.clustering import c_extrcoeff_matrix
        ref_mado = pd.read_csv(REF / "madogram_matrix.csv").values
        n = self.grid.n_grid

        # Reshape simulation data to (nrow, ncol, n_sim) — must match R layout
        # R's flat_index is column-major, so sim_data_r_order[r_idx, k]
        # corresponds to grid point r_idx (R's column-major order).
        sim_3d = np.zeros((self.grid.nrow, self.grid.ncol, self.n_sim))
        for r_idx in range(n):
            # Convert R flat index (0-based) to (row, col) in column-major order
            r_i = r_idx % self.grid.nrow
            r_j = r_idx // self.grid.nrow
            sim_3d[r_i, r_j, :] = self.sim_data_r_order[r_idx, :]

        py_mado = c_extrcoeff_matrix(sim_3d, madogram=True)

        # py_mado is indexed in Python's flat order; ref_mado in R's column-major.
        # We need to re-index. Both are n×n symmetric matrices indexed by
        # their respective flat orderings.
        # Map: py_mado[py_i, py_j] should equal ref_mado[r_i, r_j]
        #   where py_i = mapping[r_i], py_j = mapping[r_j]
        mapping = self.mapping
        ref_reindexed = np.zeros_like(ref_mado)
        for r_i in range(n):
            for r_j in range(n):
                ref_reindexed[mapping[r_i], mapping[r_j]] = ref_mado[r_i, r_j]

        np.testing.assert_allclose(py_mado, ref_reindexed, atol=1e-12,
                                   err_msg="Madogram matrix mismatch")

    def test_extremal_coefficient_matrix(self):
        from weatherisk.clustering import c_extrcoeff_matrix
        ref_ec = pd.read_csv(REF / "extremal_coefficient_matrix.csv").values
        n = self.grid.n_grid

        sim_3d = np.zeros((self.grid.nrow, self.grid.ncol, self.n_sim))
        for r_idx in range(n):
            r_i = r_idx % self.grid.nrow
            r_j = r_idx // self.grid.nrow
            sim_3d[r_i, r_j, :] = self.sim_data_r_order[r_idx, :]

        py_ec = c_extrcoeff_matrix(sim_3d, madogram=False)

        mapping = self.mapping
        ref_reindexed = np.zeros_like(ref_ec)
        for r_i in range(n):
            for r_j in range(n):
                ref_reindexed[mapping[r_i], mapping[r_j]] = ref_ec[r_i, r_j]

        np.testing.assert_allclose(py_ec, ref_reindexed, atol=1e-12,
                                   err_msg="Extremal coefficient matrix mismatch")


# ═══════════════════════════════════════════════════════════════════════════
#  7. ELLIPSE DISSIMILARITY (LEC DISTANCE)
# ═══════════════════════════════════════════════════════════════════════════

class TestEllipseDissimilarity:
    """Verify calc_distance_ellipses matches R."""

    def setup_method(self):
        _skip_if_no_ref()
        from weatherisk.grid import Grid
        self.grid = Grid(resolution=10)
        self.mapping = _r_to_py_index_map(self.grid)

    def test_ellipse_distance_matrix(self):
        from weatherisk.clustering import calc_distance_ellipses
        ref_dist = pd.read_csv(REF / "ellipse_dissimilarity_matrix.csv").values
        ref_smooth = pd.read_csv(REF / "local_estimates_smoothed.csv")
        n = self.grid.n_grid

        # Build smoothed estimates in Python's flat order
        # R's smoothed estimates are in column-major order
        py_estimates = np.zeros((n, 3))
        mapping = self.mapping
        for r_idx in range(n):
            py_idx = mapping[r_idx]
            py_estimates[py_idx, 0] = ref_smooth.iloc[r_idx]["a_sm"]
            py_estimates[py_idx, 1] = ref_smooth.iloc[r_idx]["b_sm"]
            py_estimates[py_idx, 2] = ref_smooth.iloc[r_idx]["g_sm"]

        py_dist = calc_distance_ellipses(py_estimates, res=21)

        # Re-index reference matrix from R order to Python order
        ref_reindexed = np.zeros_like(ref_dist)
        for r_i in range(n):
            for r_j in range(n):
                ref_reindexed[mapping[r_i], mapping[r_j]] = ref_dist[r_i, r_j]

        np.testing.assert_allclose(py_dist, ref_reindexed, atol=0.5,
                                   err_msg="Ellipse dissimilarity matrix mismatch")


# ═══════════════════════════════════════════════════════════════════════════
#  8. SMOOTHING
# ═══════════════════════════════════════════════════════════════════════════

class TestSmoothing:
    """Verify smooth_local_estimates matches R."""

    def setup_method(self):
        _skip_if_no_ref()
        from weatherisk.grid import Grid
        self.grid = Grid(resolution=10)
        self.mapping = _r_to_py_index_map(self.grid)

    def test_smoothing_a_and_b(self):
        """Test that smoothed a and b values match R (non-angular averaging)."""
        from weatherisk.estimation import smooth_local_estimates
        ref_raw = pd.read_csv(REF / "local_estimates_all.csv")
        ref_smooth = pd.read_csv(REF / "local_estimates_smoothed.csv")
        n = self.grid.n_grid
        mapping = self.mapping

        # Map raw estimates from R to Python order
        py_raw = np.zeros((n, 3))
        for r_idx in range(n):
            py_idx = mapping[r_idx]
            py_raw[py_idx, 0] = ref_raw.iloc[r_idx]["a_est"]
            py_raw[py_idx, 1] = ref_raw.iloc[r_idx]["b_est"]
            py_raw[py_idx, 2] = ref_raw.iloc[r_idx]["g_est"]

        # Read smoothing_dist from R scalar parameters
        scalars = pd.read_csv(REF / "scalar_parameters.csv")
        smoothing_dist = int(scalars.loc[scalars["parameter"] == "smoothing_dist", "value"].iloc[0])
        py_smooth = smooth_local_estimates(py_raw, smoothing_dist=smoothing_dist, grid=self.grid)

        # Map expected smoothed values from R to Python order
        expected = np.zeros((n, 3))
        for r_idx in range(n):
            py_idx = mapping[r_idx]
            expected[py_idx, 0] = ref_smooth.iloc[r_idx]["a_sm"]
            expected[py_idx, 1] = ref_smooth.iloc[r_idx]["b_sm"]
            expected[py_idx, 2] = ref_smooth.iloc[r_idx]["g_sm"]

        # a and b should match closely (simple arithmetic mean)
        np.testing.assert_allclose(py_smooth[:, 0], expected[:, 0], atol=1e-8,
                                   err_msg="Smoothed 'a' mismatch")
        np.testing.assert_allclose(py_smooth[:, 1], expected[:, 1], atol=1e-8,
                                   err_msg="Smoothed 'b' mismatch")

    def test_smoothing_gamma(self):
        """Test smoothed gamma (angle wrapping)."""
        from weatherisk.estimation import smooth_local_estimates
        ref_raw = pd.read_csv(REF / "local_estimates_all.csv")
        ref_smooth = pd.read_csv(REF / "local_estimates_smoothed.csv")
        n = self.grid.n_grid
        mapping = self.mapping

        py_raw = np.zeros((n, 3))
        for r_idx in range(n):
            py_idx = mapping[r_idx]
            py_raw[py_idx, 0] = ref_raw.iloc[r_idx]["a_est"]
            py_raw[py_idx, 1] = ref_raw.iloc[r_idx]["b_est"]
            py_raw[py_idx, 2] = ref_raw.iloc[r_idx]["g_est"]

        # Read smoothing_dist from R scalar parameters
        scalars = pd.read_csv(REF / "scalar_parameters.csv")
        smoothing_dist = int(scalars.loc[scalars["parameter"] == "smoothing_dist", "value"].iloc[0])
        py_smooth = smooth_local_estimates(py_raw, smoothing_dist=smoothing_dist, grid=self.grid)

        expected_g = np.zeros(n)
        for r_idx in range(n):
            py_idx = mapping[r_idx]
            expected_g[py_idx] = ref_smooth.iloc[r_idx]["g_sm"]

        # Gamma uses circular averaging, allow slightly more tolerance
        np.testing.assert_allclose(py_smooth[:, 2], expected_g, atol=1e-6,
                                   err_msg="Smoothed 'gamma' mismatch")


# ═══════════════════════════════════════════════════════════════════════════
#  9. HIERARCHICAL CLUSTERING
# ═══════════════════════════════════════════════════════════════════════════

class TestClustering:
    """Verify clustering matches R hclust results."""

    def setup_method(self):
        _skip_if_no_ref()
        from weatherisk.grid import Grid
        self.grid = Grid(resolution=10)
        self.mapping = _r_to_py_index_map(self.grid)

    def test_lec_cluster_count(self):
        """LEC clustering produces the same k as R."""
        from weatherisk.clustering import (
            clustering, cluster_number_threshold_method
        )
        ref_params = pd.read_csv(REF / "lec_clustering_params.csv")
        k_r = int(ref_params["k_lec"].iloc[0])
        q10_r = float(ref_params["q10_threshold"].iloc[0])

        # Load ellipse dissimilarity (already in R order)
        ref_dist = pd.read_csv(REF / "ellipse_dissimilarity_matrix.csv").values

        hc = clustering(ref_dist, method="average")
        k_py = cluster_number_threshold_method(hc, q10_r)
        assert k_py == k_r, f"LEC k: Python={k_py}, R={k_r}"

    def test_lec_merge_heights(self):
        """LEC merge heights match R's hclust."""
        from weatherisk.clustering import clustering
        ref_dist = pd.read_csv(REF / "ellipse_dissimilarity_matrix.csv").values
        ref_hc = pd.read_csv(REF / "hclust_lec_details.csv")

        hc = clustering(ref_dist, method="average")
        # hc is scipy linkage matrix: [idx1, idx2, height, size]
        py_heights = np.sort(hc[:, 2])
        r_heights = np.sort(ref_hc["height"].values)

        np.testing.assert_allclose(py_heights, r_heights, atol=1e-6,
                                   err_msg="LEC merge heights mismatch")

    def test_saunders_cluster_count(self):
        """EDC/Saunders clustering produces similar k to R.

        UPGMA tie-breaking differs between R's hclust and scipy's linkage
        when the madogram has many tied distances (10 simulations).
        We allow ±1 cluster difference.
        """
        from weatherisk.clustering import (
            clustering, cluster_number_threshold_method
        )
        ref_params = pd.read_csv(REF / "saunders_clustering_params.csv")
        k_r = int(ref_params["k_saunders"].iloc[0])
        q30_r = float(ref_params["q30_threshold"].iloc[0])

        ref_dist = pd.read_csv(REF / "madogram_matrix.csv").values
        hc = clustering(ref_dist, method="average")
        k_py = cluster_number_threshold_method(hc, q30_r)
        assert abs(k_py - k_r) <= 1, f"Saunders k: Python={k_py}, R={k_r} (>1 apart)"

    def test_saunders_merge_heights(self):
        """EDC merge heights approximately match R's hclust.

        Madogram distances have many ties (rank-based, 10 sims),
        so UPGMA tie-breaking differs between R and scipy.
        Heights can diverge by up to ~0.015 (b_end=5 creates more ties).
        """
        from weatherisk.clustering import clustering
        ref_dist = pd.read_csv(REF / "madogram_matrix.csv").values
        ref_hc = pd.read_csv(REF / "hclust_saunders_details.csv")

        hc = clustering(ref_dist, method="average")
        py_heights = np.sort(hc[:, 2])
        r_heights = np.sort(ref_hc["height"].values)

        np.testing.assert_allclose(py_heights, r_heights, atol=0.015,
                                   err_msg="Saunders merge heights mismatch")

    def test_lec_cluster_assignments_equivalent(self):
        """LEC cluster assignments produce the same partition as R.

        Cluster label numbers may differ, but the PARTITION must be identical:
        two grid points in the same cluster in R must be in the same cluster
        in Python, and vice versa.
        """
        from weatherisk.clustering import clustering
        from scipy.cluster.hierarchy import fcluster

        ref_params = pd.read_csv(REF / "lec_clustering_params.csv")
        k_r = int(ref_params["k_lec"].iloc[0])
        ref_clusters = pd.read_csv(REF / "clusters_lec.csv")
        r_labels = ref_clusters["cluster"].values  # R column-major order

        ref_dist = pd.read_csv(REF / "ellipse_dissimilarity_matrix.csv").values
        hc = clustering(ref_dist, method="average")
        py_labels = fcluster(hc, t=k_r, criterion="maxclust")

        # Check partition equivalence
        n = len(r_labels)
        for i in range(n):
            for j in range(i + 1, n):
                r_same = (r_labels[i] == r_labels[j])
                py_same = (py_labels[i] == py_labels[j])
                assert r_same == py_same, \
                    f"Partition mismatch at ({i},{j}): R_same={r_same}, Py_same={py_same}"

    def test_saunders_cluster_assignments_similar(self):
        """EDC cluster assignments should be very similar to R.

        Due to UPGMA tie-breaking differences, the partitions may
        differ by a few points.  We check that ≥85% of pair relations
        agree (same/different cluster).  With b_end=5 (original R
        parameters) the madogram has more rank ties than b_end=7,
        causing larger R-vs-scipy divergence.
        """
        from weatherisk.clustering import clustering
        from scipy.cluster.hierarchy import fcluster

        ref_params = pd.read_csv(REF / "saunders_clustering_params.csv")
        k_r = int(ref_params["k_saunders"].iloc[0])
        ref_clusters = pd.read_csv(REF / "clusters_saunders.csv")
        r_labels = ref_clusters["cluster"].values

        ref_dist = pd.read_csv(REF / "madogram_matrix.csv").values
        hc = clustering(ref_dist, method="average")
        py_labels = fcluster(hc, t=k_r, criterion="maxclust")

        n = len(r_labels)
        total_pairs = n * (n - 1) // 2
        mismatches = 0
        for i in range(n):
            for j in range(i + 1, n):
                r_same = (r_labels[i] == r_labels[j])
                py_same = (py_labels[i] == py_labels[j])
                if r_same != py_same:
                    mismatches += 1

        agreement = 1.0 - mismatches / total_pairs
        assert agreement >= 0.85, (
            f"Pair agreement {agreement:.3f} < 0.85 "
            f"({mismatches}/{total_pairs} mismatches)"
        )


# ═══════════════════════════════════════════════════════════════════════════
#  10. LOG-LIKELIHOOD IN CLUSTERS
# ═══════════════════════════════════════════════════════════════════════════

class TestLogLikelihoodInClusters:
    """Verify llh_in_cluster matches R for given parameters and data."""

    def setup_method(self):
        _skip_if_no_ref()
        from weatherisk.grid import Grid
        self.grid = Grid(resolution=10)
        self.mapping = _r_to_py_index_map(self.grid)

    def test_llh_in_cluster_values(self):
        """Log-likelihood per LEC cluster matches R."""
        from weatherisk.estimation import llh_in_cluster

        ref_llh = pd.read_csv(REF / "llh_in_clusters_lec.csv")
        ref_clusters = pd.read_csv(REF / "clusters_lec.csv")

        # Load simulation data in R order
        sim_ref = pd.read_csv(REF / "simulation_nonstat_seed42.csv")
        sim_cols = [c for c in sim_ref.columns if c.startswith("sim")]
        n_sim = len(sim_cols)
        n = self.grid.n_grid

        sim_data = np.zeros((n, n_sim))
        for k, col in enumerate(sim_cols):
            sim_data[:, k] = sim_ref[col].values

        # Reshape to 3D: [nrow, ncol, n_sim] in R's row/col order
        sim_3d = np.zeros((self.grid.nrow, self.grid.ncol, n_sim))
        for r_idx in range(n):
            r_i = r_idx % self.grid.nrow
            r_j = r_idx // self.grid.nrow
            sim_3d[r_i, r_j, :] = sim_data[r_idx, :]

        r_clusters = ref_clusters["cluster"].values  # R column-major order
        resolution = self.grid.resolution
        max_dist = 4 * ((self.grid.x_ax[-1] - self.grid.x_ax[0]) / (resolution - 1))

        for _, row in ref_llh.iterrows():
            cl = int(row["cluster"])
            locest = np.array([row["a"], row["b"], row["g"]])

            # Get R indices for this cluster (0-based)
            which_cl_r = np.where(r_clusters == cl)[0]

            # Convert R flat indices to (i, j) in R's column-major order
            r_rows = which_cl_r % self.grid.nrow
            r_cols = which_cl_r // self.grid.nrow

            # Extract X, Y coordinates (R order)
            X_cl = self.grid.X.flatten('F')[which_cl_r]
            Y_cl = self.grid.Y.flatten('F')[which_cl_r]

            # Build z matrix: [n_points_in_cluster, n_sim]
            z_cl = np.zeros((len(which_cl_r), n_sim))
            for k, r_idx in enumerate(which_cl_r):
                r_i = r_idx % self.grid.nrow
                r_j = r_idx // self.grid.nrow
                z_cl[k, :] = sim_3d[r_i, r_j, :]

            py_llh = llh_in_cluster(
                z_cl, df=5.0, alpha=1.0,
                X=X_cl, Y=Y_cl,
                locest=locest,
                max_dist=max_dist,
                average=True,
            )

            np.testing.assert_allclose(
                py_llh, row["llh"], atol=1e-4, rtol=1e-4,
                err_msg=f"LLH cluster {cl}: Python={py_llh}, R={row['llh']}"
            )


# ═══════════════════════════════════════════════════════════════════════════
#  11. FULL PIPELINE INTEGRATION
# ═══════════════════════════════════════════════════════════════════════════

class TestPipelineIntegration:
    """End-to-end test: same simulation data → same clusters."""

    def setup_method(self):
        _skip_if_no_ref()
        from weatherisk.grid import Grid
        self.grid = Grid(resolution=10)
        self.mapping = _r_to_py_index_map(self.grid)

    def test_madogram_from_simulation_to_clusters(self):
        """Full EDC pipeline: simulation → madogram → clustering → partition."""
        from weatherisk.clustering import (
            c_extrcoeff_matrix, clustering, cluster_number_threshold_method,
        )
        from scipy.cluster.hierarchy import fcluster

        # Load R simulation and reshape
        sim_ref = pd.read_csv(REF / "simulation_nonstat_seed42.csv")
        sim_cols = [c for c in sim_ref.columns if c.startswith("sim")]
        n_sim = len(sim_cols)
        n = self.grid.n_grid

        sim_3d = np.zeros((self.grid.nrow, self.grid.ncol, n_sim))
        for r_idx in range(n):
            r_i = r_idx % self.grid.nrow
            r_j = r_idx // self.grid.nrow
            for k, col in enumerate(sim_cols):
                sim_3d[r_i, r_j, k] = sim_ref.iloc[r_idx][col]

        # Step 1: Compute madogram
        py_mado = c_extrcoeff_matrix(sim_3d, madogram=True)

        # Step 2: Re-index to R order for threshold computation
        ref_mado = pd.read_csv(REF / "madogram_matrix.csv").values
        ref_reindexed = np.zeros_like(ref_mado)
        mapping = self.mapping
        for r_i in range(n):
            for r_j in range(n):
                ref_reindexed[mapping[r_i], mapping[r_j]] = ref_mado[r_i, r_j]

        np.testing.assert_allclose(py_mado, ref_reindexed, atol=1e-12)

        # Step 3: Cluster
        ref_params = pd.read_csv(REF / "saunders_clustering_params.csv")
        k_r = int(ref_params["k_saunders"].iloc[0])

        # Use Python's madogram directly for clustering
        hc = clustering(py_mado, method="average")
        q30 = np.quantile(py_mado[np.triu_indices(n, k=1)], 0.30)
        k_py = cluster_number_threshold_method(hc, q30)

        # UPGMA tie-breaking can differ → allow ±1 cluster
        assert abs(k_py - k_r) <= 1, f"k mismatch: Python={k_py}, R={k_r} (>1 apart)"
