"""Tests comparing CMIP6 pipeline functions against R reference outputs.

Written BEFORE code changes — these tests must:
  - FAIL on the current codebase (proving each diff exists)
  - PASS after each corresponding fix is applied

Testing methodology:
  - EDC: compare _edc_matrix_flat / _edc_condensed_flat against the
    R-validated c_extrcoeff_matrix(madogram=True) on identical data.
  - MLE: compare optimize_local_mle against the R-validated
    pairwise_density_optim_local on the same pair arrays.
  - STL: compare _detrend_grid_fast against statsmodels STL.
  - Config: verify mle_ensemble defaults.
  - Mini pipeline: end-to-end comparison against R reference CSVs
    generated by tests/generate_cmip6_mini_reference.R.

Ground truth sources:
  - tests/reference_data/ (R reference CSVs from generate_r_reference.R)
  - weatherisk.clustering.c_extrcoeff_matrix (R-validated in test_r_cross_validation.py)
  - weatherisk.density.pairwise_density_optim_local (R-validated, has parscale/retry)

Diff inventory:
  1. _edc_matrix_flat applies EC-1 transform   (R: raw madogram)
  2. optimize_local_mle b lower bound = 0.0    (R: 0.01)
  3. optimize_local_mle lacks parscale          (R: (ub-lb)/100)
  4. optimize_local_mle lacks boundary retry    (R: up to 5 extra starts)
  5. CMIP6Config.mle_ensemble = 3               (R: 5)
  6. _detrend_grid_fast uses running mean       (Paper/R: STL)
  7. Rust backend: jac=True (forward-diff grad) (Python: jac=False)
     Both must use the same gradient strategy for identical results.
"""

from __future__ import annotations

import contextlib
import inspect
from pathlib import Path

import numpy as np
import pandas as pd
import pytest
from scipy.spatial.distance import squareform

REF = Path(__file__).parent / "reference_data"
CMIP6_MINI_REF = REF / "cmip6_mini"

# ── Rust availability ─────────────────────────────────────────────────────

try:
    import weatherisk_core as _rc  # noqa: F401
    HAS_RUST = True
except ImportError:
    HAS_RUST = False


# Backend IDs used by parametrized tests.
_BACKENDS = ["python"]
if HAS_RUST:
    _BACKENDS.append("rust")


@contextlib.contextmanager
def _force_backend(name: str):
    """Temporarily force weatherisk.backend to use a specific backend.

    Patches the module-level ``_USE_RUST`` flag so that
    ``_nll_and_grad_factory`` / ``calc_distance_ellipses`` dispatch
    to the requested engine for the duration of the context.
    """
    import weatherisk.backend as _be
    old = _be._USE_RUST
    _be._USE_RUST = (name == "rust")
    try:
        yield
    finally:
        _be._USE_RUST = old


def _skip_if_no_ref():
    """Skip if main R reference data has not been generated."""
    if not (REF / "grid_coordinates.csv").exists():
        pytest.skip(
            "R reference data not generated — run: "
            "Rscript tests/generate_r_reference.R"
        )


def _skip_if_no_mini_ref():
    """Skip if mini CMIP6 R reference data has not been generated."""
    if not (CMIP6_MINI_REF / "detrended.csv").exists():
        pytest.skip(
            "Mini CMIP6 reference data not generated — run: "
            "Rscript tests/generate_cmip6_mini_reference.R"
        )


def _load_r_simulation(grid):
    """Load R simulation data and reshape to (nrow, ncol, n_sim)."""
    sim_ref = pd.read_csv(REF / "simulation_nonstat_seed42.csv")
    sim_cols = [c for c in sim_ref.columns if c.startswith("sim")]
    n_sim = len(sim_cols)

    sim_3d = np.zeros((grid.nrow, grid.ncol, n_sim))
    for r_idx in range(grid.n_grid):
        r_i = r_idx % grid.nrow   # column-major: row = idx % nrow
        r_j = r_idx // grid.nrow  # col = idx // nrow
        for k, col in enumerate(sim_cols):
            sim_3d[r_i, r_j, k] = sim_ref.iloc[r_idx][col]

    return sim_3d, n_sim


def _build_pair_arrays(sim_3d, grid, xy_pos, abstand):
    """Build (zi, zj, xl, yl) pair arrays for a grid point.

    Replicates the pair construction in pairwise_density_optim_local
    so we can feed the same inputs to optimize_local_mle.
    """
    i0, j0 = grid.number_grid(xy_pos)
    n_sim = sim_3d.shape[2]

    sel_indices = []
    for dx in range(-abstand, abstand + 1):
        for dy in range(-abstand, abstand + 1):
            if 0 < dx * dx + dy * dy <= abstand * abstand:
                ni, nj = i0 + dy, j0 + dx
                if 0 <= ni < grid.nrow and 0 <= nj < grid.ncol:
                    sel_indices.append(grid.grid_number(ni, nj))

    if not sel_indices:
        return None, None, None, None

    sel_indices = np.array(sel_indices)
    ci, cj = grid.number_grid(xy_pos)
    z_centre = sim_3d[ci, cj, :]

    sel_rows = np.array([grid.number_grid(idx) for idx in sel_indices])
    z_neighbours = sim_3d[sel_rows[:, 0], sel_rows[:, 1], :]

    zi = z_neighbours.reshape(-1)
    zj = np.tile(z_centre, len(sel_indices))
    xl = np.repeat(grid.X_flat[sel_indices] - grid.X_flat[xy_pos], n_sim)
    yl = np.repeat(grid.Y_flat[sel_indices] - grid.Y_flat[xy_pos], n_sim)

    return zi, zj, xl, yl


# ═══════════════════════════════════════════════════════════════════════════
#  1. EDC: _edc_matrix_flat must match c_extrcoeff_matrix(madogram=True)
# ═══════════════════════════════════════════════════════════════════════════

class TestEDCAgainstRValidated:
    """Compare CMIP6 pipeline EDC functions to the R-validated
    c_extrcoeff_matrix(madogram=True) on the R simulation data.

    c_extrcoeff_matrix is verified against R's madogram_matrix.csv
    in test_r_cross_validation.py::TestMadogramMatrix.

    Currently FAILS because _edc_matrix_flat / _edc_condensed_flat apply
    the EC-1 transform (values in [0, 1]) instead of returning raw
    madogram values (in [0, 0.5)).
    """

    def setup_method(self):
        _skip_if_no_ref()
        from weatherisk.grid import Grid
        self.grid = Grid(resolution=10)
        self.sim_3d, self.n_sim = _load_r_simulation(self.grid)

    def test_edc_matrix_flat_matches_validated_madogram(self):
        """_edc_matrix_flat must produce identical values to
        c_extrcoeff_matrix(madogram=True) on the same R simulation data."""
        from weatherisk.clustering import c_extrcoeff_matrix
        from weatherisk.cmip6_pipeline import _edc_matrix_flat

        # R-validated reference (known correct — matches R's madogram_matrix.csv)
        # c_extrcoeff_matrix flattens with order='F' (column-major = R order)
        mado_ref = c_extrcoeff_matrix(self.sim_3d, madogram=True)

        # CMIP6 pipeline: _edc_matrix_flat takes (n_years, n_cells)
        # Flatten sim_3d in column-major order to match internal ordering
        frechet_2d = self.sim_3d.reshape(
            self.grid.n_grid, self.n_sim, order='F'
        ).T  # → (n_sim, n_grid) with columns in column-major cell order

        edc_pipe = _edc_matrix_flat(frechet_2d)

        np.testing.assert_allclose(
            edc_pipe, mado_ref, atol=1e-12,
            err_msg=(
                f"_edc_matrix_flat does not match c_extrcoeff_matrix(madogram=True). "
                f"Pipeline max={edc_pipe.max():.4f}, "
                f"reference max={mado_ref[np.triu_indices_from(mado_ref, k=1)].max():.4f}. "
                f"The pipeline applies EC-1; it must return raw madogram."
            ),
        )

    def test_edc_condensed_flat_matches_validated_madogram(self):
        """Condensed (upper-triangle) form must also match the reference."""
        from weatherisk.clustering import c_extrcoeff_matrix
        from weatherisk.cmip6_pipeline import _edc_condensed_flat

        mado_ref = c_extrcoeff_matrix(self.sim_3d, madogram=True)
        ref_condensed = squareform(mado_ref)

        frechet_2d = self.sim_3d.reshape(
            self.grid.n_grid, self.n_sim, order='F'
        ).T
        edc_condensed = _edc_condensed_flat(frechet_2d)

        np.testing.assert_allclose(
            edc_condensed, ref_condensed, atol=1e-12,
            err_msg=(
                f"_edc_condensed_flat does not match condensed madogram. "
                f"Pipeline max={edc_condensed.max():.4f}, "
                f"reference max={ref_condensed.max():.4f}."
            ),
        )

    def test_edc_clustering_k_matches_r(self):
        """EDC clustering via pipeline functions must give the same k
        as R's saunders_clustering_params.csv (±1 for UPGMA tie-breaking)."""
        from weatherisk.clustering import (
            c_extrcoeff_matrix, clustering, cluster_number_threshold_method,
        )
        from weatherisk.cmip6_pipeline import _edc_condensed_flat

        # R reference k
        ref_params = pd.read_csv(REF / "saunders_clustering_params.csv")
        k_r = int(ref_params["k_saunders"].iloc[0])

        # Python reference path (R-validated)
        mado_ref = c_extrcoeff_matrix(self.sim_3d, madogram=True)
        mado_cond = squareform(mado_ref)
        q30_ref = float(np.quantile(mado_cond, 0.30))
        hc_ref = clustering(mado_cond)
        k_ref = cluster_number_threshold_method(hc_ref, q30_ref)

        # Pipeline path
        frechet_2d = self.sim_3d.reshape(
            self.grid.n_grid, self.n_sim, order='F'
        ).T
        edc_pipe = _edc_condensed_flat(frechet_2d)
        q30_pipe = float(np.quantile(edc_pipe, 0.30))
        hc_pipe = clustering(edc_pipe)
        k_pipe = cluster_number_threshold_method(hc_pipe, q30_pipe)

        assert k_pipe == k_ref, (
            f"Pipeline EDC k={k_pipe} (q30={q30_pipe:.4f}) ≠ "
            f"validated madogram k={k_ref} (q30={q30_ref:.4f}). "
            f"R k_saunders={k_r}. "
            f"Pipeline uses EC-1 scale; must use raw madogram."
        )


# ═══════════════════════════════════════════════════════════════════════════
#  2. MLE: optimize_local_mle must match R-validated pairwise_density_optim_local
# ═══════════════════════════════════════════════════════════════════════════

@pytest.mark.parametrize("backend", _BACKENDS)
class TestMLEAgainstRValidated:
    """Compare optimize_local_mle (CMIP6 pipeline) to
    pairwise_density_optim_local (R-validated) on the R simulation data.

    pairwise_density_optim_local has:
      - parscale = (ub - lb) / 100
      - boundary retry (up to 5 extra starts)
      - b lower bound = 0.01

    optimize_local_mle lacks all three.

    We build the same pair arrays for both functions from the R reference
    simulation data, then compare their (a, b, γ) estimates.

    Parametrized over backend={python, rust} to verify both gradient paths.
    """

    def setup_method(self):
        _skip_if_no_ref()
        from weatherisk.grid import Grid
        self.grid = Grid(resolution=10)
        self.sim_3d, self.n_sim = _load_r_simulation(self.grid)
        self.ref_pts = pd.read_csv(REF / "local_estimates_selected_points.csv")
        scalars = pd.read_csv(REF / "scalar_parameters.csv")
        self.abstand = int(
            scalars.loc[scalars["parameter"] == "locest_abst", "value"].iloc[0]
        )

    def test_optimize_local_mle_matches_validated_python(self, backend):
        """optimize_local_mle must produce estimates close to
        pairwise_density_optim_local at the R-reference selected points.

        pairwise_density_optim_local is already R-validated (it has parscale,
        boundary retry, b ≥ 0.01).  optimize_local_mle is the CMIP6 pipeline
        version that lacks these features.

        We call both with the same pair arrays and compare.  Any disagreement
        proves the algorithmic diffs matter.
        """
        from weatherisk.backend import optimize_local_mle
        from weatherisk.density import pairwise_density_optim_local

        mismatches = []
        for _, row in self.ref_pts.iterrows():
            x, y = row["X"], row["Y"]
            xy_pos = self.grid.koord_num(x, y)

            zi, zj, xl, yl = _build_pair_arrays(
                self.sim_3d, self.grid, xy_pos, self.abstand,
            )
            if zi is None:
                continue

            # R-validated version (correct — has parscale, retry, b ≥ 0.01)
            est_validated = pairwise_density_optim_local(
                self.sim_3d, 5.0, 1.0, x, y, self.grid,
                abstand=self.abstand, ensemble=5,
                lower_bounds=(0.01, 0.01),
                upper_bounds=(15.0, 15.0),
            )

            # CMIP6 pipeline version (under test) — with specified backend
            with _force_backend(backend):
                est_backend = optimize_local_mle(
                    zi, zj, xl, yl, 5.0, 1.0, ensemble=5, seed=42,
                )

            if not np.allclose(est_backend, est_validated, atol=0.5):
                mismatches.append({
                    "point": int(row["grid_point"]),
                    "x": x, "y": y,
                    "validated": est_validated.tolist(),
                    "backend": est_backend.tolist(),
                })

        assert len(mismatches) == 0, (
            f"optimize_local_mle [{backend}] differs from "
            f"pairwise_density_optim_local "
            f"at {len(mismatches)}/{len(self.ref_pts)} selected points:\n"
            + "\n".join(
                f"  Point {m['point']} ({m['x']:.2f},{m['y']:.2f}): "
                f"validated=({m['validated'][0]:.3f}, {m['validated'][1]:.3f}, "
                f"{m['validated'][2]:.3f}) vs "
                f"backend=({m['backend'][0]:.3f}, {m['backend'][1]:.3f}, "
                f"{m['backend'][2]:.3f})"
                for m in mismatches
            )
        )


# ═══════════════════════════════════════════════════════════════════════════
#  3. Config defaults must match R's parameters.R
# ═══════════════════════════════════════════════════════════════════════════

class TestConfigDefaults:
    """CMIP6Config.mle_ensemble and PipelineConfig.mle_ensemble must be 5.

    R code (parameters.R line 26):  locest_ensemble = 5
    """

    def test_cmip6_mle_ensemble(self):
        from weatherisk.cmip6_pipeline import CMIP6Config
        cfg = CMIP6Config()
        assert cfg.mle_ensemble == 5, (
            f"CMIP6Config.mle_ensemble={cfg.mle_ensemble}, R uses 5"
        )

    def test_cpc_mle_ensemble(self):
        from weatherisk.cpc_pipeline import PipelineConfig
        cfg = PipelineConfig()
        assert cfg.mle_ensemble == 5, (
            f"PipelineConfig.mle_ensemble={cfg.mle_ensemble}, R uses 5"
        )


# ═══════════════════════════════════════════════════════════════════════════
#  4. Detrending: _detrend_grid_fast must use STL, not running mean
# ═══════════════════════════════════════════════════════════════════════════

class TestDetrending:
    """Contzen et al. (2025) specifies STL detrending (Cleveland et al. 1990).
    The current _detrend_grid_fast uses a cumsum-based running mean.
    """

    def test_detrend_output_matches_stl_not_running_mean(self):
        """_detrend_grid_fast output must be closer to STL than to a
        running mean on synthetic monthly precipitation data."""
        pytest.importorskip("statsmodels")
        from statsmodels.tsa.seasonal import STL
        from weatherisk.cmip6_pipeline import _detrend_grid_fast

        rng = np.random.default_rng(42)
        n_years, n_months = 50, 600
        t = np.arange(n_months, dtype=float)

        seasonal = 5.0 * np.sin(2 * np.pi * t / 12)
        trend = 0.001 * t + 0.00001 * t ** 2
        noise = rng.normal(0, 1.5, n_months)
        pr_1d = np.maximum(20.0 + seasonal + trend + noise, 0.1)

        # Pipeline
        result = _detrend_grid_fast(
            pr_1d.reshape(n_months, 1, 1), period=12, verbose=False,
        )
        pipe_det = result[:, 0, 0]

        # STL reference
        stl_det = pr_1d - STL(pr_1d, period=12, robust=True).fit().trend

        # Running-mean reference
        half = 60
        pad = np.concatenate([pr_1d[half - 1::-1], pr_1d, pr_1d[-1:-half - 1:-1]])
        cs = np.concatenate([[0], np.cumsum(pad)])
        rm_trend = (cs[121:] - cs[:-121]) / 121
        rm_det = pr_1d - rm_trend[: len(pr_1d)]

        dist_to_stl = np.max(np.abs(pipe_det - stl_det))
        dist_to_rm = np.max(np.abs(pipe_det - rm_det))

        assert dist_to_stl < dist_to_rm, (
            f"Pipeline output is closer to running mean "
            f"(dist_rm={dist_to_rm:.4f}) than to STL "
            f"(dist_stl={dist_to_stl:.4f}). Paper specifies STL."
        )


# ═══════════════════════════════════════════════════════════════════════════
#  5. Mini CMIP6 pipeline: end-to-end R comparison
# ═══════════════════════════════════════════════════════════════════════════

class TestMiniCMIP6Pipeline:
    """End-to-end comparison against R reference outputs generated by
    tests/generate_cmip6_mini_reference.R.

    Workflow: monthly precip → STL detrend → annual maxima → GEV →
    Fréchet → EDC madogram → clustering → k.
    LEC path: Fréchet → local MLE → smoothing → ellipse dissimilarity → k.

    Each test replays one step using the CMIP6 pipeline's Python code
    and compares against the R intermediate output.

    Skipped if the R reference data has not been generated.
    """

    def setup_method(self):
        _skip_if_no_mini_ref()

    def test_stl_detrending_matches_r(self):
        """_detrend_grid_fast output must match R's STL detrended data."""
        from weatherisk.cmip6_pipeline import _detrend_grid_fast

        # Load R's input and output
        params = pd.read_csv(CMIP6_MINI_REF / "scalar_params.csv")
        n_months = int(params.loc[params["parameter"] == "n_months", "value"].iloc[0])
        n_grid = int(params.loc[params["parameter"] == "n_grid", "value"].iloc[0])
        nrow = int(params.loc[params["parameter"] == "nrow_grid", "value"].iloc[0])
        ncol = int(params.loc[params["parameter"] == "ncol_grid", "value"].iloc[0])

        pr_flat = pd.read_csv(CMIP6_MINI_REF / "monthly_pr.csv").values
        r_det_flat = pd.read_csv(CMIP6_MINI_REF / "detrended.csv").values

        # Reshape from R column-major to (n_months, nrow, ncol)
        pr_3d = np.zeros((n_months, nrow, ncol))
        r_det_3d = np.zeros((n_months, nrow, ncol))
        for r_idx in range(n_grid):
            r_i = r_idx % nrow
            r_j = r_idx // nrow
            pr_3d[:, r_i, r_j] = pr_flat[:, r_idx]
            r_det_3d[:, r_i, r_j] = r_det_flat[:, r_idx]

        # Run Python pipeline detrending
        py_det = _detrend_grid_fast(pr_3d, period=12, verbose=False)

        # Compare — should match R's STL output
        max_diff = np.max(np.abs(py_det - r_det_3d))
        np.testing.assert_allclose(
            py_det, r_det_3d, atol=0.5,
            err_msg=(
                f"_detrend_grid_fast differs from R's STL. "
                f"Max absolute diff = {max_diff:.4f}. "
                f"Pipeline uses running mean; R uses STL."
            ),
        )

    def test_edc_madogram_matches_r(self):
        """EDC madogram from pipeline functions must match R's madogram."""
        from weatherisk.cmip6_pipeline import _edc_matrix_flat

        params = pd.read_csv(CMIP6_MINI_REF / "scalar_params.csv")
        n_years = int(params.loc[params["parameter"] == "n_years", "value"].iloc[0])
        n_grid = int(params.loc[params["parameter"] == "n_grid", "value"].iloc[0])
        nrow = int(params.loc[params["parameter"] == "nrow_grid", "value"].iloc[0])

        frechet_flat = pd.read_csv(CMIP6_MINI_REF / "frechet.csv").values
        r_mado = pd.read_csv(CMIP6_MINI_REF / "madogram_matrix.csv").values

        # _edc_matrix_flat takes (n_years, n_cells) — feed in R column-major order
        edc_pipe = _edc_matrix_flat(frechet_flat)

        np.testing.assert_allclose(
            edc_pipe, r_mado, atol=1e-10,
            err_msg=(
                f"Pipeline EDC matrix differs from R's madogram. "
                f"Pipeline max={edc_pipe.max():.4f}, "
                f"R max={r_mado[np.triu_indices_from(r_mado, k=1)].max():.4f}. "
                f"Pipeline applies EC-1 transform; R returns raw madogram."
            ),
        )

    def test_edc_k_matches_r(self):
        """EDC cluster count k from pipeline must match R's k_EDC."""
        from weatherisk.clustering import clustering, cluster_number_threshold_method
        from weatherisk.cmip6_pipeline import _edc_condensed_flat

        params = pd.read_csv(CMIP6_MINI_REF / "scalar_params.csv")
        r_edc_params = pd.read_csv(CMIP6_MINI_REF / "edc_clustering_params.csv")
        k_r = int(r_edc_params["k_edc"].iloc[0])

        frechet_flat = pd.read_csv(CMIP6_MINI_REF / "frechet.csv").values
        edc = _edc_condensed_flat(frechet_flat)
        q30 = float(np.quantile(edc, 0.30))
        hc = clustering(edc)
        k_pipe = max(2, cluster_number_threshold_method(hc, q30))

        assert k_pipe == k_r, (
            f"Pipeline EDC k={k_pipe} ≠ R k_EDC={k_r}. "
            f"Pipeline q30={q30:.4f}."
        )

    def test_gev_frechet_matches_r(self):
        """Python's fit_gev + to_frechet must match R's GEV + Fréchet.

        Both implementations use MLE for GEV fitting (Python: scipy
        genextreme.fit; R: hand-coded NLL + Nelder-Mead).  The Fréchet
        transform is mathematically equivalent (CDF-based and direct
        formula give identical results given the same GEV params).

        Empirically the max relative Fréchet diff is ~0.1%, so rtol=0.01
        (1%) is generous.  This is an *irreducible* difference from the
        fitting algorithm, NOT a bug — it just needs to be small.
        """
        from weatherisk.extremes import fit_gev, to_frechet

        params = pd.read_csv(CMIP6_MINI_REF / "scalar_params.csv")
        n_grid = int(params.loc[params["parameter"] == "n_grid", "value"].iloc[0])

        am = pd.read_csv(CMIP6_MINI_REF / "annual_maxima.csv").values
        r_gev = pd.read_csv(CMIP6_MINI_REF / "gev_params.csv")
        r_frechet = pd.read_csv(CMIP6_MINI_REF / "frechet.csv").values

        py_frechet = np.zeros_like(r_frechet)
        py_gev = np.zeros((n_grid, 3))
        for s in range(n_grid):
            loc, scale, shape = fit_gev(am[:, s])
            py_gev[s] = [loc, scale, shape]
            py_frechet[:, s] = to_frechet(am[:, s], loc, scale, shape)

        r_gev_arr = np.column_stack([
            r_gev["loc"], r_gev["scale"], r_gev["shape"],
        ])

        # GEV params should agree within ~0.001 (irreducible fitting diff)
        np.testing.assert_allclose(
            py_gev, r_gev_arr, atol=0.01,
            err_msg="GEV params differ from R beyond fitting tolerance.",
        )

        # Fréchet values: max relative diff is ~0.1% empirically
        np.testing.assert_allclose(
            py_frechet, r_frechet, rtol=0.01,
            err_msg=(
                f"Fréchet differs from R. "
                f"Max abs diff={np.abs(py_frechet - r_frechet).max():.4f}."
            ),
        )

    @pytest.mark.parametrize("backend", _BACKENDS)
    def test_local_mle_matches_r(self, backend):
        """Local MLE estimates from pipeline must match R's estimates.

        Uses _local_mle_one_cmip6 (→ optimize_local_mle) for each cell.
        R uses pairwise_density_optim_local with parscale, retry, b≥0.01.
        Python's optimize_local_mle lacks these → estimates will differ.

        Parametrized over backend={python, rust}.
        """
        from weatherisk.cmip6_pipeline import CMIP6Config, _local_mle_one_cmip6

        grid_df = pd.read_csv(CMIP6_MINI_REF / "grid_coordinates.csv")
        frechet = pd.read_csv(CMIP6_MINI_REF / "frechet.csv").values
        r_est = pd.read_csv(CMIP6_MINI_REF / "local_estimates_all.csv")
        lec_params = pd.read_csv(CMIP6_MINI_REF / "lec_scalar_params.csv")
        abstand = int(
            lec_params.loc[lec_params["parameter"] == "locest_abst", "value"].iloc[0]
        )

        grid_coords = np.column_stack([
            grid_df["Y"].values, grid_df["X"].values,
        ])

        cfg = CMIP6Config(
            neighbor_radius=float(abstand),
            smoothing_radius=2.0,
            df=5.0,
            alpha=1.0,
        )

        n_grid = len(grid_df)
        py_est = np.zeros((n_grid, 3))
        with _force_backend(backend):
            for cidx in range(n_grid):
                py_est[cidx] = _local_mle_one_cmip6(
                    frechet, cidx, grid_coords, cfg,
                )

        r_est_arr = np.column_stack([
            r_est["a_est"].values, r_est["b_est"].values, r_est["g_est"].values,
        ])

        ab_diff = np.abs(py_est[:, :2] - r_est_arr[:, :2])
        max_a_diff = ab_diff[:, 0].max()
        max_b_diff = ab_diff[:, 1].max()
        n_mismatch = np.sum(np.any(ab_diff > 1.0, axis=1))

        worst_idx = np.argmax(ab_diff[:, 1])
        np.testing.assert_allclose(
            py_est[:, :2], r_est_arr[:, :2], atol=1.0,
            err_msg=(
                f"Local MLE [{backend}] (a,b) differ from R "
                f"at {n_mismatch}/{n_grid} cells. "
                f"Max a diff={max_a_diff:.3f}, max b diff={max_b_diff:.3f}. "
                f"Worst cell {worst_idx}: "
                f"py=({py_est[worst_idx, 0]:.3f}, {py_est[worst_idx, 1]:.3f}) "
                f"R=({r_est_arr[worst_idx, 0]:.3f}, {r_est_arr[worst_idx, 1]:.3f}). "
                f"optimize_local_mle lacks parscale/retry and has b_lower=0.0."
            ),
        )

    @pytest.mark.parametrize("backend", _BACKENDS)
    def test_ellipse_dissimilarity_matches_r(self, backend):
        """Ellipse dissimilarity from Python pipeline must match R's.

        This depends on local MLE + smoothing being correct.
        Parametrized over backend={python, rust}.
        """
        from weatherisk.clustering import calc_distance_ellipses
        from weatherisk.cmip6_pipeline import (
            CMIP6Config, _local_mle_one_cmip6, _smooth_estimates_cmip6,
        )

        grid_df = pd.read_csv(CMIP6_MINI_REF / "grid_coordinates.csv")
        frechet = pd.read_csv(CMIP6_MINI_REF / "frechet.csv").values
        r_ell = pd.read_csv(
            CMIP6_MINI_REF / "ellipse_dissimilarity_matrix.csv"
        ).values
        lec_params = pd.read_csv(CMIP6_MINI_REF / "lec_scalar_params.csv")
        abstand = int(
            lec_params.loc[lec_params["parameter"] == "locest_abst", "value"].iloc[0]
        )
        smooth_dist = int(
            lec_params.loc[
                lec_params["parameter"] == "smoothing_dist", "value"
            ].iloc[0]
        )

        grid_coords = np.column_stack([
            grid_df["Y"].values, grid_df["X"].values,
        ])
        cfg = CMIP6Config(
            neighbor_radius=float(abstand),
            smoothing_radius=float(smooth_dist),
            df=5.0,
            alpha=1.0,
        )

        n_grid = len(grid_df)
        py_est = np.zeros((n_grid, 3))
        with _force_backend(backend):
            for cidx in range(n_grid):
                py_est[cidx] = _local_mle_one_cmip6(
                    frechet, cidx, grid_coords, cfg,
                )

        py_smoothed = _smooth_estimates_cmip6(
            py_est, grid_coords, cfg, verbose=False,
        )
        py_ell = calc_distance_ellipses(py_smoothed, res=21)

        max_diff = np.abs(py_ell - r_ell).max()
        np.testing.assert_allclose(
            py_ell, r_ell, atol=5.0,
            err_msg=(
                f"Ellipse dissimilarity [{backend}] differs from R. "
                f"Max diff={max_diff:.1f}. "
                f"This propagates from MLE estimate differences."
            ),
        )

    @pytest.mark.parametrize("backend", _BACKENDS)
    def test_lec_k_matches_r(self, backend):
        """LEC cluster count k from pipeline must match R's k_LEC.

        Parametrized over backend={python, rust}.
        """
        from weatherisk.clustering import (
            calc_distance_ellipses, clustering, cluster_number_threshold_method,
        )
        from weatherisk.cmip6_pipeline import (
            CMIP6Config, _local_mle_one_cmip6, _smooth_estimates_cmip6,
        )

        grid_df = pd.read_csv(CMIP6_MINI_REF / "grid_coordinates.csv")
        frechet = pd.read_csv(CMIP6_MINI_REF / "frechet.csv").values
        r_lec_params = pd.read_csv(CMIP6_MINI_REF / "lec_clustering_params.csv")
        k_r = int(r_lec_params["k_lec"].iloc[0])
        lec_params = pd.read_csv(CMIP6_MINI_REF / "lec_scalar_params.csv")
        abstand = int(
            lec_params.loc[lec_params["parameter"] == "locest_abst", "value"].iloc[0]
        )
        smooth_dist = int(
            lec_params.loc[
                lec_params["parameter"] == "smoothing_dist", "value"
            ].iloc[0]
        )

        grid_coords = np.column_stack([
            grid_df["Y"].values, grid_df["X"].values,
        ])
        cfg = CMIP6Config(
            neighbor_radius=float(abstand),
            smoothing_radius=float(smooth_dist),
            df=5.0,
            alpha=1.0,
        )

        n_grid = len(grid_df)
        py_est = np.zeros((n_grid, 3))
        with _force_backend(backend):
            for cidx in range(n_grid):
                py_est[cidx] = _local_mle_one_cmip6(
                    frechet, cidx, grid_coords, cfg,
                )

        py_smoothed = _smooth_estimates_cmip6(
            py_est, grid_coords, cfg, verbose=False,
        )
        py_ell = calc_distance_ellipses(py_smoothed, res=21)
        ell_cond = py_ell[np.triu_indices_from(py_ell, k=1)]
        q30 = float(np.quantile(ell_cond, 0.30))
        hc = clustering(ell_cond)
        k_pipe = max(2, cluster_number_threshold_method(hc, q30))

        assert k_pipe == k_r, (
            f"Pipeline LEC [{backend}] k={k_pipe} (q30={q30:.2f}) ≠ "
            f"R k_LEC={k_r}. "
            f"Differences propagate from MLE bugs in optimize_local_mle."
        )
